### ISSUE TITLE
stretch-pgdg packages not found for version 9.5 to 11

### ISSUE THREAD

**Issue by gozeller** [docker-library/postgres#1012]
Hello,

for software upgrade purposes we need to use version "postgres:9.5" - we use a Dockerfile like this:

```
FROM postgres:9.5
USER root
RUN localedef -i de_AT -c -f UTF-8 -A /usr/share/locale/locale.alias de_AT.UTF-8
RUN apt-get update
# RUN apt-get -y install ca-certificates
RUN apt-get -y install lsof wget
RUN wget --no-check-certificate --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN apt-get -y install perl
RUN apt-get -y install postgresql-plperl-9.5
ENV LANG de_AT.utf8
```

Unfortunately we've got this error since days:

```
#7 3.665 W: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
#7 3.665 E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages  404  Not Found [IP: 147.75.85.69 80]
```

I tried some newer versions but still get this error until version 11.

Is there a way for us how can use version 9.5 for the next months?

Thanks for your precious help!

**Comment by tianon** [comment]
PostgreSQL 9.5 has been EOL since February of last year (9.6 since November of last year, and even 10 since 4 days ago; see https://www.postgresql.org/support/versioning/).

In the future or for further assistance, these sorts of questions/requests would be more appropriately posted to a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).
