### ISSUE TITLE
Best practice for deploying a databases?

### ISSUE THREAD

**Issue by MaxGladkikh** [docker-library/postgres#1016]
How you advise to unroll DB is better? Own container for each database? Or is it possible to have several databases in one container?

**Comment by wglambert** [comment]
Postgres is a database management system so it can have multiple databases https://www.postgresql.org/docs/current/sql-createdatabase.html

For questions like these you might try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
