### ISSUE TITLE
Postgres 16 Docker Image gives error: unrecognized configuration parameter "lc_ctype" 

### ISSUE THREAD

**Issue by birarisonali26** [docker-library/postgres#1127]
Steps to reproduce:
1. `docker pull postgres:16`
2. `docker run -d --name postgresnew -e LANG=en_US.utf8 -e POSTGRES_INITDB_ARGS="--locale-provider=icu --icu-locale=en-US" -e POSTGRES_PASSWORD=welcome1 postgres:16`
3. `docker exec -ti postgresnew bash `
4. Once inside container, execute: `psql -U postgres`
5. this will launch postgresql promt
6. Enter following command: `show lc_ctype`
7. It gives following error:
```
postgres=# show lc_ctype
postgres-# ;
ERROR:  unrecognized configuration parameter "lc_ctype"
```
<img width="579" alt="image" src="https://github.com/docker-library/postgres/assets/63604006/a28af155-e620-4dea-92be-d0b15814e0fc">

**Same query works for Postgres14 Version**
<img width="501" alt="image" src="https://github.com/docker-library/postgres/assets/63604006/57ffbfee-2bc5-49d3-9b0f-b806d904cf63">

**Comment by LaurentGoderre** [comment]
Not sure this is a problem with the image itself. Using your example, running `show all;` shoows a list and `lc_ctype` idsn't there but other ones like `lc_numeric` are so `show lc_numeric;` works.

Listing the databases shows the ctype though

```
   Name    |  Owner   | Encoding | Locale Provider |  Collate   |   Ctype    | ICU Locale | ICU Rules |   Access privileges   
-----------+----------+----------+-----------------+------------+------------+------------+-----------+-----------------------
 postgres  | postgres | UTF8     | icu             | en_US.utf8 | en_US.utf8 | en-US      |           | 
 template0 | postgres | UTF8     | icu             | en_US.utf8 | en_US.utf8 | en-US      |           | =c/postgres          +
           |          |          |                 |            |            |            |           | postgres=CTc/postgres
 template1 | postgres | UTF8     | icu             | en_US.utf8 | en_US.utf8 | en-US      |           | =c/postgres          +
           |          |          |                 |            |            |            |           | postgres=CTc/postgres
```

**Comment by ImreSamu** [comment]
> ERROR:  unrecognized configuration parameter "lc_ctype"

In Postgresql 16, many server variables will be removed, which are included in the [PG16 Release Notes](https://www.postgresql.org/docs/16/release-16.html).

_____

_Version 16 contains a number of changes that may affect compatibility with previous releases._ 
* _Remove read-only server variables `lc_collate` and `lc_ctype` (Peter Eisentraut)
Collations and locales can vary between databases so having them as read-only server variables was unhelpful._
* _Remove the server variable `vacuum_defer_cleanup_age` (Andres Freund)
This has been unnecessary since [hot_standby_feedback](https://www.postgresql.org/docs/16/runtime-config-replication.html#GUC-HOT-STANDBY-FEEDBACK) and [replication slots](https://www.postgresql.org/docs/16/warm-standby.html#STREAMING-REPLICATION-SLOTS) were added._

* _Remove server variable `promote_trigger_file` (Simon Riggs)
This was used to promote a standby to primary, but is now easier accomplished with [pg_ctl promote](https://www.postgresql.org/docs/16/app-pg-ctl.html) or [pg_promote()](https://www.postgresql.org/docs/16/functions-admin.html#FUNCTIONS-RECOVERY-CONTROL-TABLE)._

* ....

see the full changes: https://www.postgresql.org/docs/16/release-16.html

**Comment by LaurentGoderre** [comment]
Closing since this is an expected change and there are alternate ways to access the info

**Comment by birarisonali26** [comment]
Thanks LaurentGoderre and ImreSamu.
This helps.
