### ISSUE TITLE
Build is fine, however running a container throws an error

### ISSUE THREAD

**Issue by hnasr** [docker-library/postgres#135]
First thanks for this great repo

So I downloaded both Dockerfile and docker-entrypoint.sh and build an image using this command.

`docker build .`

that builds fine. 

then using the resulting imageid I try to run a container with this command

`docker run e7474737b073`

```
that throws an error
no such file or directory docker: Error response from daemon: Container command not found or does not exist..
```

I'm doing something wrong? 
Thanks

P.S. Key server was not responding so I changed them to hkp://p80.pool.sks-keyservers.net:80 I don't know if this has anything to do with the problem I'm facing

System: Boot2docker
Windows 10 

$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

**Comment by tianon** [comment]
That sounds suspiciously like a boot2docker-specific problem.  Before going too far into the specifics of what's happening when you build -- any particular reason you need to build this image instead of using the existing artifacts as-is?  With automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) it's reasonably easy to have an up-to-date image built `FROM` this one with whatever you need added.

**Comment by hnasr** [comment]
Thanks for your reply. Needless to mention that I'm new to Docker.

I just need to edit the Dockerfile to remove the data Volumes. The reason I want to do that is to backup my container with its databases so if I remove it and reload it move with it. 

This was a long discussion in a question I posted in the stack overflow link below
 
http://stackoverflow.com/questions/35952601/backup-a-postgres-container-with-its-databases/35952782#35952782

**Comment by tianon** [comment]
You should be able to do `ENV PGDATA /somewhere/else` in order to get this outside of the volume, but it is kind of strange (and will have a performance impact) to keep that data inside the layering filesystem (so I'd really strongly recommend an out-of-band backup solution instead of trying to keep the container and the data in the same backup).

**Comment by hnasr** [comment]
Thanks Tianon,

I'm still trying to understand the performance implication here as its critical to me. 

- So what I do is spawn a new 9.3 postgres db container
- Use a special software to author the database (ArcGIS)
- use Build Commit to commit the changes to the image. 
- Now I have an image with "good" data.
- I have around 100 tests that should run against this data and each test make some changes to this data. 
- For Each test I will create a new container out of my image. Run the Test, then destroy my container since the data is now invalid.
- I do the same for the second test I would reload a fresh container out of my image, run the test and so on 
- The Problem is If I use volume, and I create a container out of this image, somehow my database is not showing up when I connect to my postgres instance in the container. So I solved that by removing the volume all together, this will include my database "inside" the image. 

How would that affect performance? Is it because the data has to get extracted from the image every time I run a container?

if there is another solution to this please do suggest it. 

Thank you again,
-Hussein

**Comment by tianon** [comment]
Sorry for the massive delay -- this affects performance because by doing so, your database ends up being stored in the read-write layer of the graph driver of Docker, which does a lot of extra accounting to track changes (which you don't care about for a database).

Since the original issue here is solved, I'm going to close.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
