### ISSUE TITLE
Add 9.5.2, to match Amazon RDS

### ISSUE THREAD

**Issue by mcd-php** [docker-library/postgres#155]
Please add this exact version, so user may choose it to ensure seamless migration between DB in own EC instance and RDS managed one.

See https://aws.amazon.com/ru/about-aws/whats-new/2016/04/rds-postgresql-9-5-support/ for exact version.

**Comment by yosifkit** [comment]
The `9.5.2` image is still available to pull from the [Docker Hub](https://hub.docker.com/r/library/postgres/tags/).  We cannot add it as a "supported version" since we only support what upstream supports; which is the latest release of each major version: http://www.postgresql.org/support/versioning/.

**Comment by yosifkit** [comment]
Closing old issue.
