### ISSUE TITLE
cluster locale

### ISSUE THREAD

**Issue by liuhuasong** [docker-library/postgres#20]
How to set the locale of database cluster? the default is "en_US.utf8", but I want to set it before start the image.

**Comment by yosifkit** [comment]
This looks solved.

**Comment by geraldodev** [comment]
Hi, 

Congrats on the quality of the image.
I was trying to make my own with centos because of specific locale needs.
Until I found the initdb is delayed until the 1st start with cmd "postgres" (which is default btw).

IMHO this use case deserves a section on How to extend this image.

Regards,

Geraldo
