### ISSUE TITLE
Include PG_MAJOR version in PGDATA path

### ISSUE THREAD

**Issue by rmoriz** [docker-library/postgres#201]
Currently PGDATA does not contain a pg version and defaults to:

```
ENV PGDATA /var/lib/postgresql/data
VOLUME /var/lib/postgresql/data
```

Because the data is persistant AND bound to the pg version, this makes it very hard to have an in-place upgrade (e.g. using https://hub.docker.com/r/tianon/postgres-upgrade/) and requires to have a different volume for each pg version.

I suggest to include the version of pg into the PGDATA directory name by default, e.g.

```
ENV PG_MAJOR 9.5
...
ENV PGDATA /var/lib/postgresql/data/$PG_MAJOR
VOLUME /var/lib/postgresql/data
```

**Comment by tianon** [comment]
Sorry for the super long tail on replying to this. :disappointed:  I think https://github.com/docker-library/postgres/issues/37 is worth linking to from this discussion (since it's where upgrading has been discussed in a lot of depth).

The change you've described should be really easy to create your own image of via something like the following:
```dockerfile
FROM postgres:9.6
ENV PGDATA $PGDATA/$PG_MAJOR
```

I think we're well-entrenched enough now that we can't easily make this change for these images without massive downstream breakage, but the above shows it's really easy for users to do so themselves if this is something they desire.  It might make sense for https://hub.docker.com/r/tianon/postgres-upgrade/'s README to describe that (perhaps using `-e` on `docker run` instead of a `Dockerfile`), so it's easier to find/figure out. :sweat_smile:
