### ISSUE TITLE
Persistent volume using driver issue

### ISSUE THREAD

**Issue by spiderhc** [docker-library/postgres#235]
Hello, I'm having the error below, it seems like a bug in the image, can someone help me?

### Description: 
I want to persist my postgres data files in a volume driver (cloud), but when I create the container it just stops after created, and viewing _docker logs_ command I see the following error:

- _postgres: could not access the server configuration file "/var/lib/postgresql/data/pgdata/postgresql.conf": No such file or directory_

My system information: Server OS Ubuntu 16.04 + Docker 1.10.2 + Azurefile Docker Volume Driver

If I try with a local volume, it works fine!!!! To get the error, the volume path must be the same as the PGDATA environment variable!

### Steps to get it:

- [ ] Install azurefile docker volume driver (I believe is it possible to get same error with Flocker):
https://github.com/Azure/azurefile-dockervolumedriver

- [ ] Execute the following docker commands:

- docker volume create --name databases_pg_data -d azurefile -o share=db-data-psql

- docker run --name psql-websites-01 -v databases_pg_data:/var/lib/postgresql/data/pgdata -e PGDATA=/var/lib/postgresql/data/pgdata -d postgres:9.6.1

**Comment by yosifkit** [comment]
That looks like a permission issue; I would bet that the container root user is silently denied the `chown` to the postgres user and then the postgres user is unable to write to the `PGDATA` directory.  You'll need to ensure that the volume is created with the correct user permissions. Azurefile has all the options:
```console
$ # taken from the azurefile readme
$ docker volume create -d azurefile \
  -o share=sharename \
  -o uid=999 \
  -o gid=999 \
  -o filemode=0600 \
  -o dirmode=0755 \
  -o nolock=true \
  -o remotepath=directory
$ # not sure if you need anything besides:
-o uid=999 -o gid=999 -o dirmode=0700 
$ # this will match the postgres user in the image and the permissions on the directory:
$ # https://github.com/docker-library/postgres/blob/a00e979002aaa80840d58a5f8cc541342e06788f/docker-entrypoint.sh#L32

```

**Comment by spiderhc** [comment]
@yosifkit  I tried:

- -o uid=999 -o gid=999 -o dirmode=0700 (your suggestion)

- -o uid=999 -o gid=999 -o dirmode=0777 -o filemode=0777

Despite what you told makes sense, this solution didn't solve the problem.

I found this from [this azurefile volume driver github issue](https://github.com/Azure/azurefile-dockervolumedriver/issues/65):

> I am guessing SMB protocol does not allow you do chmod/chown. This is why you're getting the Operation not permitted error.

Please, do you know another possible workaround?

**Comment by saikatguha** [comment]
I got postgres to work on docker+azurefile. It's not pretty, but it's a start. Would appreciate improvements.

1. uid/gid/mode issue: postgres does need the correct owner and mode. azurefile already provides the needed options. Create the volume using `-o uid=999,gid=999,filemode=0600,dirmode=0700`

2. chown/chmod issue: this problem is with initdb only. postgres itself doesn't care. I modified docker-entrypoint.sh near line 18 to run initdb outside the volume, and mv the data back in.
   ```
	rm -rf /tmp/init 
	mkdir -p /tmp/init && chmod 700 /tmp/init && chown -R postgres /tmp/init
	eval "gosu postgres initdb -D /tmp/init $POSTGRES_INITDB_ARGS"
	mv /tmp/init/* $PGDATA/
   ```

3. fsync issue: fsync is enabled by default, and results in fatal error since azurefile/cifs doesn't support it. Disable fsync by passing `-o "-c fsync=off -c full_page_writes=off"` to `pg_ctl` (around line 51), and again `-c fsync=off -c full_page_writes=off` to `postgres` around line 94.

That's it! postgres should now be working on azurefile in docker.

The ugly: With fsync off, postgres will not be able to recover from sudden crashes. see [runtime-config-wal](https://www.postgresql.org/docs/9.6/static/runtime-config-wal.html) for a discussion on fsync issues. Additionally, write ordering and caching issues in cifs may result in silent data-corruption. see [pgsql-general](https://www.postgresql.org/message-id/CABUevEww2AKdVqU3n8wi-zpSsqVPKn8xxCk4io3nzv6O7UZMqQ@mail.gmail.com).

Thoughts on how to address or mitigate?

**Comment by Revocsid** [comment]
I have the same problem with the Cloudstor driver. I have the following error when the volume is created : 

`initdb : could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted`

I installed the cloudstor plugin withe the following command : 

`docker plugin install docker4x/cloudstor:18.02.0-ce-azure1 --alias cloudstor:azure --grant-all-permissions CLOUD_PLATFORM=AZURE AZURE_STORAGE_ACCOUNT_KEY="<storage_key>" AZURE_STORAGE_ACCOUNT="<storage_account>"`

On my docker-compose.yml side :

```
pg_db:
    container_name: pg_db
    image: postgres:9.6
    volumes:
      - pg_db_data:/bitnami

volumes:
    pg_db_data:
        driver: cloudstor:azure
        driver_opts:
            share: pg-db-data
```

### Version

- Output of docker version:

```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:33 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:15:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of docker-compose version

```
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

Does anyone know what is the issue ?

**Comment by yosifkit** [comment]
Closing old issue. It seems to be a problem with accessing the remote file system, Azurefile, and not something wrong in the image. We don't really have the resources to debug running postgresql on Azure using their remote file storage.

In the future, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Perhaps someone in the [Azure community](https://azure.microsoft.com/en-us/support/community/) would know more.
