### ISSUE TITLE
Non-Default PGDATA Volume Isn't Created

### ISSUE THREAD

**Issue by ihcsim** [docker-library/postgres#236]
When a non-default `PGDATA` env variable is provided as part of  `docker run`, the corresponding volume isn't created because the Dockerfile hard-coded the `VOLUME` instruction to `/var/lib/postgresql/data`.

I was hoping to update the Dockerfile to `VOLUME $PGDATA` and override the env var with `docker run -e PGDATA=/data`, which didn't seem to work, because Docker only picks up the `ENV PGDATA /var/lib/postgresql/data` provided at build time.

I could specify the data volume at runtime with something like `docker run -d --name pgsql -e PGDATA=/data/pgsql -v /data/pgsql postgres:9.6 postgres`. But an extra volume is still created for `/var/lib/postgresql/data`.
```sh
$ docker inspect pgsql
.....
"Mounts": [
{
  "Name": "a741938f89aa1c4dd5bea184100deb08a475339c88987b37c87f9166b15c154d",
  "Source": "/var/lib/docker/volumes/a741938f89aa1c4dd5bea184100deb08a475339c88987b37c87f9166b15c154d/_data",
   "Destination": "/data/pgsql",
   ....
},
{
  "Name": "4e6b185304b7686ea3729c19e1a350414589386e48006f71a4f89d0b357c1c4f",
  "Source": "/var/lib/docker/volumes/4e6b185304b7686ea3729c19e1a350414589386e48006f71a4f89d0b357c1c4f/_data",
  "Destination": "/var/lib/postgresql/data",
   ....
}
],
....
```
Then again, the extra volume is just empty and doesn't take up any disk space. 

If this is something that you'll like to fix, I can submit a PR to update the docs at [docker-library](https://github.com/docker-library/docs/tree/master/postgres) mentioning that one will need to specify the data volume at runtime with the `-v` flag and/or omit `VOLUME` from the Dockerfile altogether to let the user decide when/where to mount a data volume ~~or add a `PGDATA` build argument to ensure the right volume is created.~~

~~For example,~~
~~ARG pg_data_dir=/var/lib/postgresql/data  # use default if no build arg is provided~~
~~ENV PGDATA=$pg_data_dir~~
~~VOLUME $PGDATA~~

Not sure if there are other better ways to handle this.

**Comment by tianon** [comment]
Sorry for the really long tail.

The main thing I see folks adjusting `PGDATA` for is to _avoid_ the `VOLUME` we declare because they want to do crazy things like store the actual PostgreSQL database files inside the image (which can make it start up somewhat faster, especially for running test suites, etc).

Given that we can't make our `VOLUME` dynamic and that this is really a general "understanding of Docker and volumes" issue, I'm also hesitant to add an explicit note to the documentation.

So I'm not actually sure I understand what the ask here is?  What are you trying to accomplish by changing `PGDATA` but still using a volume?  What does that change? (from what I can see, it's functionally identical to what the image already provides by default :sweat_smile:)

**Comment by ihcsim** [comment]
> What are you trying to accomplish...

If memory served, it probably had something to do with the mount point of the block storage I had to work with. My thought back then was that the `PGDATA` environment variable was used as the argument of `VOLUME` as described in the Docker [docs](https://docs.docker.com/engine/reference/builder/#environment-replacement).

**Comment by tianon** [comment]
Gotcha -- in that case, you probably simply wanted to do something like `-v /data/pgsql:/var/lib/postgresql/data` instead. :+1:

(I'm going to close this now. :sweat_smile: :heart:)
