### ISSUE TITLE
alpine 9.6.1 invalid MAJOR MINOR path

### ISSUE THREAD

**Issue by austinnichols101** [docker-library/postgres#250]
The dockerfile for alpine 9.6.1 sets the path to:

`ENV PATH /usr/lib/postgresql/$PG_MAJOR/bin:$PATH`

Unfortunately the postgresql binaries are not being installed in the same folders as the original (non-alpine) images so this path is incorrect.  

Preferred fix would be to configure the install paths so that they are the same between the distros.

**Comment by yosifkit** [comment]
I would guess that the `PATH` env in the Alpine image is a bad copy from the Debian Dockerfile, since we set `--prefix=/usr/local` on the configure script.  We use `/usr/local/` to ensure that anything installed will not be overwritten when system software is installed (see [`/usr/local/` spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html)).  Even though the [Alpine-provided postgresql package](https://pkgs.alpinelinux.org/contents?file=postgres&path=&name=postgresql&branch=v3.5&repo=main&arch=x86_64) does not have any current conflicts, it is best practice to install non-packages to `/usr/local/`.

**Comment by austinnichols101** [comment]
That what it looked like to me also (bad copy from Debian Dockerfile).  

Shouldn't we add the MAJOR:MINOR sub-folders when using /usr/local ?

**Comment by wglambert** [comment]
Issue seems to be resolved now

Debian stretch
```console
$ docker run --rm -d -e MYSQL_ROOT_PASSWORD=pass --name postgres postgres
$ docker exec -it postgres bash
root@b7e6430c69dd:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/10/bin
```
Alpine
```console
$ docker run --rm -d -e MYSQL_ROOT_PASSWORD=root --name postgres1 postgres:alpine
$ docker exec -it postgres1 sh
/ # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
