### ISSUE TITLE
docker-entrypoint.sh: line 105: cannot create temp file for here-document: Permission denied

### ISSUE THREAD

**Issue by zolamk** [docker-library/postgres#258]
I pulled the `postgres:9-alpine` image and tried to create a container from it like this

`sudo docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword postgres:9-alpine`

but i get the following output and the container never starts

    The files belonging to this database system will be owned by user "postgres".
    This user must also own the server process.

    The database cluster will be initialized with locale "en_US.utf8".
    The default database encoding has accordingly been set to "UTF8".
    The default text search configuration will be set to "english".

    Data page checksums are disabled.

    fixing permissions on existing directory /var/lib/postgresql/data ... ok
    creating subdirectories ... ok
    selecting default max_connections ... 100
    selecting default shared_buffers ... 128MB
    selecting dynamic shared memory implementation ... posix
    creating configuration files ... ok
    running bootstrap script ... ok
    performing post-bootstrap initialization ... sh: locale: not found
    No usable system locales were found.
    Use the option "--debug" to see details.
    ok
    syncing data to disk ... 
    WARNING: enabling "trust" authentication for local connections
    You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
    ok

    Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

    waiting for server to start....LOG:  database system was shut down at 2017-01-31 13:15:39 UTC
    LOG:  MultiXact member wraparound protections are now enabled
    LOG:  database system is ready to accept connections
    LOG:  autovacuum launcher started
    done
    server started
    /docker-entrypoint.sh: line 105: cannot create temp file for here-document: Permission denied`

**Comment by yosifkit** [comment]
I haven't seen this before, but might stem from a mount being read-only. Can you give the output of the following commands?
```console
$ docker version
$ docker info
$ docker run -it --rm postgres:9-alpine mount
```

**Comment by zolamk** [comment]
Here is the output @yosifkit

`$ docker version`

    Client:
    Version:      1.12.1
    API version:  1.24
    Go version:   go1.6.3
    Git commit:   23cf638
    Built:        Mon, 10 Oct 2016 21:38:17 +1300
    OS/Arch:      linux/amd64

    Server:
    Version:      1.12.1
    API version:  1.24
    Go version:   go1.6.3
    Git commit:   23cf638
    Built:        Mon, 10 Oct 2016 21:38:17 +1300
    OS/Arch:      linux/amd64

`$ docker info`

    Containers: 4
    Running: 1
    Paused: 0
    Stopped: 3
    Images: 31
    Server Version: 1.12.1
    Storage Driver: aufs
    Root Dir: /omega/recovery/docker/aufs
    Backing Filesystem: extfs
    Dirs: 35
    Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
    Volume: local
    Network: bridge null host overlay
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Security Options: apparmor
    Kernel Version: 4.8.0-22-generic
    Operating System: Ubuntu 16.10
    OSType: linux
    Architecture: x86_64
    CPUs: 2
    Total Memory: 3.731 GiB
    Name: alpha27
    ID: TOAT:LHLA:HX3N:T6HK:KCIZ:7PE5:QT5R:CHAM:YNSI:3I2O:VXH5:UUCX
    Docker Root Dir: /omega/recovery/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support
    Insecure Registries:
    127.0.0.0/8

`$ docker run -it --rm postgres:9-alpine mount`

    none on / type aufs (rw,relatime,si=2f82dadd70871a49,dio,dirperm1)
    proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
    tmpfs on /dev type tmpfs (rw,nosuid,mode=755)
    devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
    sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
    tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
    cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
    cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
    cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
    cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
    cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
    cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
    cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
    cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
    cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
    cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
    cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
    mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
    /dev/sda6 on /etc/resolv.conf type ext4 (rw,nosuid,nodev,relatime,data=ordered)
    /dev/sda6 on /etc/hostname type ext4 (rw,nosuid,nodev,relatime,data=ordered)
    /dev/sda6 on /etc/hosts type ext4 (rw,nosuid,nodev,relatime,data=ordered)
    shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
    /dev/sda6 on /var/lib/postgresql/data type ext4 (rw,nosuid,nodev,relatime,data=ordered)
    devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
    proc on /proc/asound type proc (ro,nosuid,nodev,noexec,relatime)
    proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
    proc on /proc/fs type proc (ro,nosuid,nodev,noexec,relatime)
    proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
    proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
    proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
    tmpfs on /proc/kcore type tmpfs (rw,nosuid,mode=755)
    tmpfs on /proc/timer_list type tmpfs (rw,nosuid,mode=755)
    tmpfs on /proc/timer_stats type tmpfs (rw,nosuid,mode=755)
    tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,mode=755)

**Comment by wglambert** [comment]
Was there any update on this?

**Comment by tianon** [comment]
Closing old issue -- this appears to be an environmental problem (we cannot reproduce).

For help determining the root cause, I'd recommend hitting up [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by juffardm** [comment]
Hello zolamk,
I have exactly the same problem. Do you remember how you solved it?
Thanks a lot!

**Comment by ksilz** [comment]
> I have exactly the same problem. Do you remember how you solved it?

@juffardm @tianon I ran into the same issue. Here's how I fixed it.

On the Mac, Docker allocates at most 64 GB of disk space for images and containers. Once Docker uses up these 64 GB, you'll get errors like "No space left on device" from your containers because they can't write to their local disks anymore. The containers **can** still write to their mapped volumes, though, because those live on the host system and don't count against the 64 GB threshold.

On the Mac, you can check the available Docker disk space through *Preferences...* - *Disk*. For me, currently 39.2 out of 64 GB are used:

![Docker space on macOS](https://user-images.githubusercontent.com/1061209/69724325-9c25df80-1113-11ea-8289-1834fa7498e7.png)

So, how do you free space in the Docker disk file? You remove containers and unused images. For instance, to remove all stopped containers, you do `docker container prune`. And to remove parts of images that aren't used anymore, do a `docker image prune`. Both of these commands will tell you how much space you safed.

Now you can safe the most space by completely removing images. Use this command to show you all images, sorted by size, with the biggest image listed first: `docker images | sort -k7 -h -r`. You can then remove images individually through their ID with `docker images rm [list of image IDs]`.

I assembled this post from these three sources:
- [Original "No space left on device" lead](https://blog.cadizm.com/2019/03/06/docker-no-space-left-on-device)
- [Fix for "No space left on device" on macOS](https://www.peterbe.com/plog/no-space-left-on-device-on-osx-docker)
- [Sorting Docker images by size](https://gist.github.com/andyrbell/f30ae74c0eff82ae52238f4a7df9a313#gistcomment-2856331)

**Comment by bentocin** [comment]
I ran into exactly the same issue with `postgres:12`. 

The error message referenced [line 173](https://github.com/docker-library/postgres/blob/0d0485cb02e526f5a240b7740b46c35404aaf13f/docker-entrypoint.sh#L173) though:

```bash
/docker-entrypoint.sh: line 173: cannot create temp file for here-document: Permission denied
```

For me what solved the problem was changing the permissions of `/tmp` dir in the container like so: `chmod 1777 /tmp`

Because it seemed like the problem already exists in the `debian:10-slim` base image, I posted detailes [there](https://github.com/debuerreotype/docker-debian-artifacts/issues/83).
