### ISSUE TITLE
error acess gpg --keyserver ha.pool.sks-keyservers.net

### ISSUE THREAD

**Issue by leonmcar1** [docker-library/postgres#262]
Please, change in Dockerfiles for debian:
gpg --keyserver ha.pool.sks-keyservers.net 
to 
gpg --keyserver hkp://p80.pool.sks-keyservers.net:80.

The same error for references => https://github.com/tianon/gosu/issues/17

**Comment by yosifkit** [comment]
We use the `ha` set since it is supposed to be "highly available", but there is no similar guarantee on the `p80` set.

Is there a reason for building it and not just doing `docker pull postgres:9.6`?  You can then easily extend the image in your own Dockerfile with `FROM postgres:9.6`.

Related issues https://github.com/docker-library/mysql/issues/49, https://github.com/docker-library/mongo/issues/87
