### ISSUE TITLE
No data persisted

### ISSUE THREAD

**Issue by howshit** [docker-library/postgres#268]
Hi, first of all, thx for the image.

My problem is that when I run the image as a container, and I put data in the container.

Then, I commit the new the container as a new image.

The new images is almost identical with the old image.

There is no data in the new image.

But I want a  new image with my data.

Please kindly help me tackle the problem.

**Comment by jsm** [comment]
You should be able to mount in a directory from your host to

**Comment by SISheogorath** [comment]
This issue is based on the fact that the volumes for persistent data are defined in the Dockerfile:
https://github.com/docker-library/postgres/blob/master/9.5/Dockerfile#L62 (for example)


> Note: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

Referring to the docs: https://docs.docker.com/engine/reference/builder/#volume

That's your problem you can't use this image to prepare an image that already contains the data inside the database. It's a bad idea anyways.

As you should use another Dockerfile to make your data changes reproduceable, use a Dockerfile that extends the postgres image and copy a SQLdump to `/docker-entrypoint-initdb.d`.

For further information refer to the official image [README](https://hub.docker.com/_/postgres/) at the "How to extend this image"-section.

**Comment by tianon** [comment]
Closing given @SISheogorath's excellent summary of the issue and the fix. :heart:
