### ISSUE TITLE
Arbitrary --user change breaks my customisation script

### ISSUE THREAD

**Issue by martinffx** [docker-library/postgres#271]
So I have a simple script to install plv8 on my postgres image. It was working fine but with this Arbitrary --user change has changed the user that the script runs under from `root` to `postgres`

    # /docker-entrypoint-initdb.d/init.sh
    #! /bin/bash

    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y postgresql-contrib-9.4 postgresql-9.4-plv8

The `postgres` user doesn't have permissions to install anything.

What is the recommended way to install pg extensions when customising an image?

**Comment by tianon** [comment]
Sorry about the break!

For installing more packages, etc, I'd recommend making a new Dockerfile
that is FROM postgres:x.y which installs the extra things you need,
especially since the initdb scripts will only run when your database
directory is initialized, so if you ever recreate the container with the
same volume, you won't have your new packages installed anymore.

**Comment by martinffx** [comment]
hmmm... was hoping to avoid that.
