### ISSUE TITLE
Remove any root dependencies from docker-entrypoint.

### ISSUE THREAD

**Issue by jayunit100** [docker-library/postgres#300]
Problem: The postgres images seem to really want to use root in their entrypoints.  This is  bad for all the obvious reasons.

- If you're not root, one of the commands in docker-entrypoint.sh `chown ${id -u}` is falsely dynamic - it will only run as root. 
- There isn't a provision made that checks, if a user doesn't have proper privileges, so that postgres can continue.

So, we should make sure we don't depend/expect/silently-fail-if-we-cant-depend on root.  This is paramount for secure, production environments, and in places like kubernetes and openshift, where containers can migrate rapidly across 100s of nodes in a cluster, and where admins don't allow root.

Solution:  I think the solution is to do something similar to what rhscl does, make the container defensive, and don't hard code root specific logic into entrypoint, at all.

Without loss of generality I think this logic  applies to other images as well.

**Comment by yosifkit** [comment]
There are notes about running it as a different user in the Docker Hub documentation ([source](https://github.com/docker-library/docs/tree/aa1959a855a9b1025057d7efc9e01553ca83a257/postgres#arbitrary---user-notes)).  Many of the database and service images support this as well (assuming you set permissions correctly for any provided docker volume).

At the point of `chown -R "$(id -u)" "$PGDATA" 2>/dev/null || :` ([line 52](https://github.com/docker-library/postgres/blob/74857f4148c844921f8a4903033189d98ecdda48/docker-entrypoint.sh#L52)) it is definitely not running as root, so the `id -u` does seem strange.  But it is designed to ignore errors, given the pipe to `/dev/null` and the `|| :` ("or true").  I can't think of a case that it will actually chown something.  I do know the `chmod 700` on the next line is important since postges is picky about the permissions of `PGDATA`.
