### ISSUE TITLE
Unable to modify pg_hba.conf

### ISSUE THREAD

**Issue by FrankFang** [docker-library/postgres#325]
```
FROM postgres:9.6.4

RUN echo "host all all 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf
```
But the file content never changes.
Could you show me an example? Thanks.

Same as #105

**Comment by gbsmit03** [comment]
Try updating it using a script in the entry point `/docker-entrypoint-initdb.d`. I'm currently doing this in one of our setups.

**Comment by andreolaya** [comment]
I have the same problem, also in the file "pg_hba.conf line 95" we find:

     host all all all md5

It appears to be created automatically.

**Comment by yosifkit** [comment]
@andreolaya, for your `RUN` line, the file you are writing to is in a volume so it will not be persisted after a `RUN` step.  For the initdb.d script, you seem to be missing an item for your first line; it needs to have 5 like the second line (or needs to be `local` instead of `host`, [pg docs](https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html)):
```
host all all peer
host all all 127.0.0.1/32 md5
```
