### ISSUE TITLE
Postgres server terminating incorrectly on script error in docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by fchugunov** [docker-library/postgres#328]
When error occures in any script from docker-entrypoint-initdb.d folder, container is stopped and postgres server is terminated incorrectly. It is better to check for error and try to stop postgresql server when error occures.

**Comment by yosifkit** [comment]
All we do is source the scripts (which mean they inherit our `set -e`) and so if the script fails, the whole bash process exits which is the main process of the container and causes the container to die (which kills the postgres server).  If you need error handling in your scripts you should add that in.

Since these scripts are only ever ran on an empty database, an incorrectly stopped server can just be deleted and recreated with an updated script.


Relevant source section:
https://github.com/docker-library/postgres/blob/58ed93931d38f96981fb3e971217e6619d23f75a/docker-entrypoint.sh#L126-L134
