### ISSUE TITLE
weird login problem - sometimes i get in, somtimes i wont

### ISSUE THREAD

**Issue by kakulukia** [docker-library/postgres#336]
I have some very weird problem accessing the database inside my docker container. Postgres is set to trust all connections but still sometimes asks for a password and sometimes wont let me in afterwards even with the right password. 
I have set logging to debug5, but the only weird stuff i see is

    db_1     | DEBUG:  reaping dead processes
    db_1     | DEBUG:  server process (PID 119) exited with exit code 0

nothing obviously related to the login problem. Im using the following command to get access to the DB from within the app container:

    psql -h db -U postgres

Loggin in works flawlessly from the docker host when exposing the db port. No password request as expected and no rejects.
My pg_hba.conf has the following entries:

    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    
    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            trust
    # IPv6 local connections:
    host    all             all             ::1/128                 trust
    host all all all trust

Any ideas whats wrong here?

**Comment by yosifkit** [comment]
I'm confused, what password are you referring to?  If you start the container with a password (`POSTGRES_PASSWORD`), then the `pg_hba.conf` will be `md5` rather than `trust`, but your file has `trust` so you couldn't have started it with a password. Did you manually add one after startup.

https://github.com/docker-library/postgres/blob/bef8f02d1fe2bb4547280ba609f19abd20230180/9.6/docker-entrypoint.sh#L66-L87

Are you using the same user (`-U`) in each place? PostgreSQL "asks for the password instead of divulging that the user doesn't exist, it's a common response that avoids leaking information about existing accounts to a non-authorized person." (https://stackoverflow.com/a/12388762)

**Comment by kakulukia** [comment]
@yosifkit i tried a lot of stuff including setting a password and using it. And yes i changes that pg_hba line by hand and set it to trust to see if it helps.
The thing is that it sometimes works and sometimes not and that "sometimes" is driving me crazy! A plain and consistent NO would be cool, but a login that works sometimes is totally hard to get around!
Like i wrote above: exposing the postgres port to the host and loggin in from there always works. But loggin in from the application container works in three different ways which seem totally random:

	root@09f8f1e2095d:/code# psql -h db -U postgres vfk_portal
	psql (9.4.13, server 9.6.5)
	WARNING: psql major version 9.4, server major version 9.6.
	         Some psql features might not work.
	Type "help" for help.

	vfk_portal=# \q
	root@09f8f1e2095d:/code# psql -h db -U postgres vfk_portal
	Password for user postgres:
	psql (9.4.13, server 9.6.5)
	WARNING: psql major version 9.4, server major version 9.6.
	         Some psql features might not work.
	Type "help" for help.

	vfk_portal=# \q
	root@09f8f1e2095d:/code# psql -h db -U postgres vfk_portal
	Password for user postgres:
	psql: FATAL:  password authentication failed for user "postgres"
	root@09f8f1e2095d:/code#

1. not asking for a password
2. asking for password, but ignoring it since i entered random letters
3. not letting me in at all

3 different responses to the same way of trying to log into the database.
The actual webapp is python trying to login via psycopg2, but psql has the same problems.
I never saw a behaviour like this. Its totally okay to block me because some setting might be wrong - i can work with that! But only sometimes rejecting my login is a really weird behaviour.

**Comment by kakulukia** [comment]
I just launched an additional postgres9.6 container, just to get rid of this version warning.
The psql command has the same problems as shown above .. it just sometimes works.

**Comment by kakulukia** [comment]
i finally found the problem among the multiple running containers on my docker host, there was a second postgres container with the hostname db assigned and those two instances where fighting each other in the sense that only sometimes i got connected to the right database and got thrown out on all other attempts.

Docker should throw a warning for cases like this.
Lesson learned: Docker aint checking host names .. i should do that!

**Comment by mathemaphysics** [comment]
I had the same problem. Turned out that something I had installed on my laptop (Windows, sadly) installed a standard PostgreSQL database which occupied port 5432 for some time. Turns out that when I thought I was connecting to the container, I was actually connecting to that database. I got rid of it and things work now.
