### ISSUE TITLE
Start crond by Default in Alpine Docker Image

### ISSUE THREAD

**Issue by thaxy** [docker-library/postgres#353]
Hi,

I try to make sure that the ``crond`` process is always running in my container.
I can ``exec`` into the running container and just run it in the background by executing ``crond`` but if I stop and start the container the process would be gone.

Is there any convenient way so that I could run my cron jobs **inside** my container?
Someone on stackoverflow suggested me to install the extension ``pg_cron``. But all my problems would be gone if I can make sure that ``crond`` is always running.

**Comment by tianon** [comment]
I'd agree that `pg_cron` is the best option if you want the jobs to run _in_ your PostgreSQL container.

Another OK option would be to run the jobs via cron on your host using `docker exec`.

If you must run `crond` inside a container, I'd recommend instead using a separate container which runs nothing but `crond` (and thus Docker can both track its lifecycle, and restart it when/if it fails, the machine restarts, etc).  You should be able to connect to the PostgreSQL instance from a second container, but if absolutely necessary, one could use things like `--network container:some-postgres` in order to join the network namespace of the database container directly.

**Comment by tianon** [comment]
In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
