### ISSUE TITLE
Fail-fast setting for psql-client prevents automatic import on startup of full db dumps

### ISSUE THREAD

**Issue by rgielen** [docker-library/postgres#362]
https://github.com/docker-library/postgres/blob/f7dc5727b1d6b6a636350e11648845ae33477579/9.6/docker-entrypoint.sh#L104

In this line psql is advised to fail fast on errors. This is a problem for importing any dump created by pg_dumpall, since there is a 99% chance it will include a ```CREATE ROLE postgres;``` statement, causing an error. In default mode psql keeps on executing the following statements, which is perfectly fine to restore a cluster.

My expectation would be that a pg_dumpall dump can be imported smoothly when mounted at ```/docker-entrypoint-initdb.d```.

I suggest to remove the fail-on-error setting or at least make it configurable through an environment variable (IMHO with defaulting to standard psql behaviour)

**Comment by tianon** [comment]
(Sorry for the long tail.)

The goal with adding `ON_ERROR_STOP=1` is to ensure that errors are not hidden from the operator -- typically the _last_ thing you want is for something important to fail and the script to barrell onwards as if nothing is wrong (especially since that becomes harder to debug/diagnose after the fact).  I think the best suggestion I can offer here is that if the default behavior we provide isn't sufficient, it should be pretty trivial to drop in a one-liner `.sh` script to have some custom behavior which ignores errors instead. :+1:

**Comment by tianon** [comment]
(To be clear, we do the same thing with shell scripts too -- `set -e` is enabled for the very same set of reasons.)
