### ISSUE TITLE
Document how to create container with existing schema

### ISSUE THREAD

**Issue by dsvensson** [docker-library/postgres#375]
In some cases the schema creation can take well over a minute. This makes it infeasible to use in continuous integration setups. It would be great if there was a well established, documented, way to create a container based on the output of a `/docker-entrypoint-initdb.d`-initialized container.

**Comment by laroque** [comment]
Has there been any other response to this? I see a stack overflow post where you raise this issue (https://stackoverflow.com/questions/34751814/build-postgres-docker-container-with-initial-schema) which has a response with a reason for why we may not want to build the schema into the image, but nothing saying how to do it if that reason is not compelling when weighed against the slow container start time.

**Comment by tianon** [comment]
If you absolutely must bake the database files themselves into your images, you'll want to set `PGDATA` so that it no longer points at the pre-configured `VOLUME` location, thus allowing for the data to persist within the image.  The exact location you choose doesn't really matter, as long as it's not a `VOLUME`.
