### ISSUE TITLE
How to run script as root user on startup

### ISSUE THREAD

**Issue by dapalmi** [docker-library/postgres#417]
I tried to run a command as root on startup of postgres by adding something like this to my Dockerfile:

```
FROM postgres
...
CMD postgres && <command>
```

But I get following error:

> "root" execution of the PostgreSQL server is not permitted.

How do I accomplish this?

**Comment by otbutz** [comment]
I'd recommend a custom entrypoint if you really need to execute a command at *every* container start. If its only for initial setup then check "How to extend this image" at https://hub.docker.com/_/postgres/

Dockerfile
```Dockerfile
FROM postgres
# ...
COPY my-custom-entrypoint.sh /
ENTRYPOINT ["/bin/bash", "/my-custom-entrypoint.sh"]
```

my-custom-entrypoint.sh
```sh
#!/bin/bash
# do your stuff
exec /bin/bash /docker-entrypoint.sh "$@"
```

What are you planning to do? Maybe there's even a better way.

**Comment by tianon** [comment]
Indeed, @otbutz is correct -- this is by design. :heart:

I'd recommend posting to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) for further help designing your image/entrypoint to do what you're looking for. :+1:
