### ISSUE TITLE
How to create a volume without permision like root

### ISSUE THREAD

**Issue by cmardonespino** [docker-library/postgres#427]
Im working with docker to create two containers: django & postgres.

**What is my issue?**

I want to create a volume in my project to has a database persistent and commit to my repository to download in another machine and has the same database. So, when I create a volume in my docker-compose.yml inside my project, after maked `docker-compose up` the folder created with volume of postgresql in my project, this have a permision like root, so I cant commit the folder in my repository...

This is my docker-compose file:

    version: '3'
    services:

        db:
          #build: ./postgresqlDocker/
          image: postgres # Utiliza una imagen la cual en caso de no tener, la descarga
          environment:
            POSTGRES_USER: postgres #CREA UN USUARIO Y UNA BASE DE DATOS CON PRIVILEGIOS
            POSTGRES_PASSWORD: password123 # LE ASIGNA UNA PASSWORD AL USUARIO Y SU BASE DE DATOS
            POSTGRES_DB: test_db
          ports:
            - "5432:5432" # (HOST:CONTAINER)
          volumes:
            - ./data/postgres:/var/lib/postgresql/data/

        web:
          build: .
          command: python manage.py runserver 0.0.0.0:8000
          volumes:
            - .:/code
            # (HOST:CONTAINER)
          ports:
            - "8000:8000"
            # (HOST:CONTAINER)
          depends_on:
            - db

This is the definition of database connection in my settings.py:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': 'password123',
            'HOST': 'db',
            'PORT': 5432,
        }
    }

And when I want to access to postgres folder:

`cd data/postgres/
bash: cd: data/postgres/: Permission denied`

I hope can you help me!
Thanks everyone!

**Comment by qedrakmar** [comment]
This is an issue related to the uid that postgres is initializing with (probably uid:999 for docker).  The directory will be owned and populated by that user which is not the user you're logged in as.  The easiest way around this is to make sure the uids line up as discussed here: [https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes](https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes).

So, you can approach this two ways.  If you are planning to checkout a pre-existing database, you just need to make sure that the --user uid:gid you specify has permission to the directory on the host.  Ideally, you want that to be your user, but at least a user you can su to, otherwise you'll have the same problems accessing the directory on the host.

If you're going to checkout later with no pre-existing database, you need the db initialization (initdb) to run inside the container.  However, if you specify a --user uid:gid so the container runs as a user that has access on the host, that uid:gid still needs to exist in /etc/passwd inside the container, or initdb will fail.  The two ways to handle that are described in the URL above, though in the second case, you'd still want to replace 1000:1000 with your own uid:gid.

Hope that helps!

**Comment by cmardonespino** [comment]
@qedrakmar I really appreciate your help! I will try to fix the issue, because Im a novice in docker ... But thanks a lot! I will post again if I can't fix the issue

**Comment by cmardonespino** [comment]
@qedrakmar Where I must to specificate the uid:gid ? From my docker-compose file or creating a docker volume?

**Comment by qedrakmar** [comment]
The UID:GID would be specified in the compose file, as mentioned [here](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir).  Note, this docs example show just a user with no GID, but both formats are valid.

**Comment by tianon** [comment]
Closing, since this appears to be resolved.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
