### ISSUE TITLE
Create image with empty database

### ISSUE THREAD

**Issue by quanterion** [docker-library/postgres#433]
I'm using docker-compose for testing with one of containers is postgres. Each time I start compose it takes postgres image and spends some to create container out of it because it runs docker-entrypoint.sh.

So I want to speed it up and create Docker image with empty seed database:

```
FROM postgres:10.1

ENV POSTGRES_PASSWORD mypassword
ENV POSTGRES_DB shell

RUN docker-entrypoint.sh postgres

```
ENTRYPOINT ["echo DB shell started"]
However it doesn't work because command RUN docker-entrypoint.sh postgres never exits. How to do it the right way?

**Comment by tianon** [comment]
When you `RUN docker-entrypoint.sh postgres`, you're literally starting up the PostgreSQL server, which expects to run indefinitely.

As to what you're trying to accomplish, see https://github.com/docker-library/postgres/issues/375 and https://github.com/docker-library/postgres/issues/319#issuecomment-327254512.  You'll need to set `PGDATA`, and likely run `initdb` yourself (because `docker-entrypoint.sh`'s initialization code is tailored for starting up a persistent instance of PostgreSQL, as you've discovered).

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
