### ISSUE TITLE
Data is lost when a postgres container is commit has a new image.  

### ISSUE THREAD

**Issue by cbadillac** [docker-library/postgres#445]
When I commit a container as  a new image, and then I run this new image, all data that I saved in the original container are lost/erased. 

How can I commit a container without to loss all data?

**Comment by wglambert** [comment]
Are you not mounting volumes?

If so, then you're looking to mount a volume for this https://github.com/docker-library/docs/tree/master/postgres#pgdata

Containers have a read/write layer that is temporary, when the container is 'stopped' it will retain data in that layer, when it's removed and started back up; you're doing so from the image which hasn't been modified. So you'd want volumes mounted from the host onto the container.

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by yosifkit** [comment]
Duplicate of https://github.com/docker-library/postgres/issues/375,
