### ISSUE TITLE
Set UTF-8 to Postgres Docker Image

### ISSUE THREAD

**Issue by pedrofurtado** [docker-library/postgres#457]
How do I set UTF-8 system-wide postgres docker container? Do I need to create some ENV variable in my dockerfile that is based on `postgres:10.4`?

Do I just need to do something like this (below) in my Dockerfile? Nothing more else?

```Dockerfile
FROM postgres:10.4
ENV LANG C.UTF-8
````

**Comment by wglambert** [comment]
https://stackoverflow.com/a/28406007
```Dockerfile
# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8    
```

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
