### ISSUE TITLE
copy postgresql.conf into $PGDATA if found in /docker-entrypoint-initdb.d/

### ISSUE THREAD

**Issue by chesty** [docker-library/postgres#469]
Would something like this be welcome?

https://github.com/chesty/postgres/commit/83afc263915eaa8e563f98f7dfb29bd0fd8c6a98#diff-60713fb19f6c50a2473835df63ff17f9

I haven't found the docs on building the containers locally, so it's not tested, I guess I also need to edit all the docker-entrypoint.sh files in the repo? not sure.

**Comment by tianon** [comment]
If you put `postgresql.conf` into `/docker-entrypoint-initdb.d` today, it'll get ignored (which is expected), so I'd recommend that folks who need this sort of behavior ought to put `cp /docker-entrypoint-initdb.d/postgresql.conf "$PGDATA/"` into their own trivial `.sh` file in `/docker-entrypoint-initdb.d` (instead of adding explicit support for this in the image itself).

**Comment by chesty** [comment]
fair enough, I'll close this.
