### ISSUE TITLE
The docs use the legacy `--link` option in the instructions and don't provide an alternative.

### ISSUE THREAD

**Issue by arielpontes** [docker-library/postgres#486]
The [Docker documentation](https://docs.docker.com/network/links/) alerts readers that the `--link` option is "a legacy feature of Docker" that "may eventually be removed". However, the only instructions in the `postgres` image documentation use the `--link` option. The docs should be updated to include instructions on how to link a second container to the postgres one in a modern way that doesn't involve the `--link` option.

**Comment by wglambert** [comment]
`--link` is more of a "soft deprecation" wherein its usage isn't obsolete, more so that it's surpassed by docker networks in functionality. Using an example for testing container interoperability you can do a `--link` without involving network creation and cleanup. See https://github.com/docker-library/docs/issues/786#issuecomment-350491848

Closing as there are discussions over at https://github.com/docker-library/docs/issues/786, https://github.com/docker-library/docs/pull/1063
