### ISSUE TITLE
Add support for updating the postgres account password after database creation

### ISSUE THREAD

**Issue by timabbott** [docker-library/postgres#487]
It's a pretty normal workflow to initially setup a container using a dummy password present in a `docker-compose.yml`, and then later want to replace it with a secure password.  

Ideally, one would be able to do that by just updating the password in the `docker-compose.yml` file and then restarting the image, and count on the `postgres` image to automatically update the user's password with an `ALTER USER` query to match what was configured in the environment.  However, this image seems to not do that.

See https://github.com/zulip/docker-zulip/issues/140 for some context on how this would be valuable.

(Or, if this isn't the right way to solve that problem, I'd love advice on what the right path forward is).

Since I think it'd only be a couple lines of code in `entrypoint.sh` to support this, I'd be happy to help make it happen if the maintainers are interested in this feature.

**Comment by tianon** [comment]
> Since I think it'd only be a couple lines of code in `entrypoint.sh` to support this, I'd be happy to help make it happen if the maintainers are interested in this feature.

So, this is actually a little more tricky than it first appears.

On the initial database startup (think empty directory -- very obviously non-initialized database), we start a full daemon, perform the initdb actions (including running any user-specified scripts), then shut that daemon down and start postgres up again properly.

The second time the daemon runs (no longer an empty, uninitialized directory), we start postgres directly without any intermediate steps.

In order to implement what you propose, we'd have to do the full start-psql-shutdown-start dance for _every_ database startup, which is kind of heavy just for changing passwords.

**Comment by timabbott** [comment]
Well, we could just store a hash of the password in a file somewhere and compare the hash before deciding whether to do the extra work?

(Or just have the code do an appropriate `ALTER USER` after doing the "start postgres directly" step)
