### ISSUE TITLE
Strange PG_VERSION format

### ISSUE THREAD

**Issue by mmikhalko** [docker-library/postgres#515]
Why is it using version format like PG_VERSION 11.0-1.pgdg90+2? I have some problem when I use node-semver library with version postgres

**Comment by yosifkit** [comment]
That is just the `apt` package version as found in the apt repo provided by postgresql.org.

Since this is not a problem in the image I will close.  In the future, it might be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

This is roughly how the update script scrapes it:
```
$ curl -fsSL http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages | tac | tac | awk -F ': ' '$1 == "Package" { pkg = $2 } $1 == "Version" && pkg == "postgresql-11" { print $2; exit }'
11.0-1.pgdg90+2
```
