### ISSUE TITLE
 Docker container issue

### ISSUE THREAD

**Issue by naveenkumarboopathi** [docker-library/postgres#528]
when a docker PostgreSQL container get crash/stop how could i recover data . is it any possible to recover ?

**Comment by wglambert** [comment]
If your data is mounted as a volume you can try starting a new container from it, otherwise if it's corrupted then [this comment](https://dba.stackexchange.com/a/22801) might help you.

Going to close since this isn't an issue with the image and should be asked over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)
