### ISSUE TITLE
release-number tagged images

### ISSUE THREAD

**Issue by r2evans** [docker-library/postgres#551]
Thank you for this image!

I currently have `postgres:11.1` installed, but I don't know which one. My issue is not that I don't know how to find the hash or the particular version of postgres running inside the container (both are straight-forward).

Does it make sense to add release-level to your tags? For instance:

- [x] `postgres:11` is always the most recent major version
- [x] `postgres:11.1` is always the most recent major/minor version
- [ ] `postgres:11.1-13` is the 13th build (constructive number for this issue), so I know that when `postgres:11.1-14` comes out, it is new for me to pull and update my yaml files

Is it docker-best-practice (and your intent) that users re-pull their desired tag periodically (daily?) or whenever it changes? Does this somewhat hide the changes under the hood? (Is there a changelog somewhere?)

I don't know that I'm following best practices. I tend to target specific versions (I'm on `:11.1` right now); in other repos, I tend towards release-level, e.g., `:11.1-13`, and manually check. It might be a little more work for me to monitor, but it is to counter past experience (with other containers, not postgres) where I upgraded immediately only to find out that a debilitating bug was introduced and downgrading is not trivial. (Tape backups, here I come.)

**Comment by yosifkit** [comment]
As you note, we do have the major, minor, and patch (when available) series tags like `postgres:11`, `postgres:11.1`, and `postgres:9.6.11`. :smile: 

Unfortunately our build system isn't designed to do any kind of build-number tags. We possibly could have a number that is incremented each time the Dockerization changes (ie on PR to [`official-images`](https://github.com/docker-library/official-images)), but that would only capture one side of when images are built. Any image in the official-images will be rebuilt if its base image was updated. Example: if `debian:stretch-slim` is updated, which happens approximately every 30 days, then `postgres:11` would be rebuilt (and every other image in official-images that is `FROM debian:stretch-slim`).

I'd really recommend users have an update mechanism that resolves the human-friendly image tag that they want to the content addressable hash of the architecture specific image. I would caution to not use the manifest list digest, since that will change more often; not all architectures finish at the same time so most changes would just be another architecture build (like `arm64v8` or `s390x`). We try not to change images in such a way to break the users' experience, but it has happened. All image tags are subject to change, and so they should ensure that they save the digest of the last known good image and test deploying the next hash.

For `postgres:11.1` on `amd64`, the most recent would be: `docker pull postgres@sha256:bd88d517ea5385b4269e5c4022d5a0fb652ff2b9b767c53e9b3a2021c9b2450a`
Where last week, `postgres:11.1` on `amd64` was `docker pull postgres@sha256:072b8dacc23e8c4e304ab4adbefe00bc23e67b15dcec27c7398066f7f3c3dc26`

The times that these hashes show up correspond to to the [Debian bump](https://github.com/docker-library/official-images/pull/5399) and the [postgres bump to `11.1-3.pgdg90+1`](https://github.com/docker-library/official-images/pull/5365).

I got the hashes from [repo-info](https://github.com/docker-library/repo-info/blob/9426c65c0d59a26ecf5e875d5a2c1dc160c11979/repos/postgres/remote/11.1.md#postgres111---linux-amd64).

---------------------

As for a changelog, that is this repo; changes here will happen in the images on the Docker Hub once a PR is merged to official-images.

**Comment by r2evans** [comment]
That makes sense, and clarifies some of my other assumptions regarding best-practices.

Another image I use is [`gitlab/gitlab-ce`](https://hub.docker.com/r/gitlab/gitlab-ce/tags), which somehow does do the release number somehow; I'm not certain if it's "easy" and built-in or if they strong-arm it internally. (Based on your `debian:stretch-slim`/30-days comment, now I wonder if another image I'm using is *not* updating their base OS periodically ... grrrr ...) Regardless, I think I'll update my internal processes.

Thanks for the time for a detailed response!
