### ISSUE TITLE
postgres-9.6 invalid value for parameter "lc_messages": "en_US.utf8"

### ISSUE THREAD

**Issue by ghost** [docker-library/postgres#552]
The latest change to the 9.6 docker image to 9.6.12 (from 9.6.11) has resulted in our postgres server dying with:

postgres    | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
postgres    | LOG:  invalid value for parameter "lc_messages": "en_US.utf8"
postgres    | LOG:  invalid value for parameter "lc_monetary": "en_US.utf8"
postgres    | LOG:  invalid value for parameter "lc_numeric": "en_US.utf8"
postgres    | LOG:  invalid value for parameter "lc_time": "en_US.utf8"

We have no special config, just the base docker build.

Any idea how to fix this?

**Comment by sirmax2** [comment]
Look #415

**Comment by pc-trent** [comment]
I saw that, and it helped fix the problem. 

I'm now interested in how this change was tested as it would have broken every instance using this image with the default configuration.

**Comment by tianon** [comment]
This seems odd -- we literally haven't changed the `localedef` line included in our `Dockerfile`s for ~5 years.

See https://github.com/docker-library/postgres/pull/15/files#diff-1578307c887a49e90a57418e653ad7f6R15 for where it was initially added back in 2014, and looking at the blame it changed slightly in https://github.com/docker-library/postgres/pull/437/files#diff-b2875299404acb0984502587dcbdad13R40, but only to move around, it didn't actually change.

**Comment by pc-trent** [comment]
From what I can tell, the issue stems from postgres 9.6.12 (9.6.11 unaffected) that required an explicit localdef to be installed - and it appears to happen all the way until 10.2.

**Comment by tianon** [comment]
But that doesn't make any sense, because we've had some variation of the following line in our `Dockerfile` for _literally_ ~5 years:

https://github.com/docker-library/postgres/blob/cc305ee1c59d93ac1808108edda6556b879374a4/Dockerfile-debian.template#L48

```dockerfile
RUN ... \
	localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
```

Which is very similar to what's described over in #415 as having "fixed" it.

Do we have a simple `docker run` line that demonstrates the issue easily so we can dig into it more?

**Comment by wglambert** [comment]
Closing since the Author's account is now a ghost and this could be an issue of doing an `apt-get upgrade` in the container which caused the issue for https://github.com/docker-library/postgres/issues/415#issuecomment-467993290 and https://github.com/docker-library/postgres/issues/690#issuecomment-590583373
