### ISSUE TITLE
pg_basebackup access. pgpass

### ISSUE THREAD

**Issue by xlievo** [docker-library/postgres#553]
pg_hba.conf: host replication replica 0.0.0.0/0 md5
.pgpass: *:*:*:replica:e3980c76

Executing pg_basebackup access .pgpass in docker-entrypoint-initdb.d seems to require a superuser

Pg_basebackup: could not connect to server: FATAL: password authentication failed for user "replica"

root execution can

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by xlievo** [comment]
master pg_hba.conf
host replication replica 0.0.0.0/0 md5

slave .pgpass
*:*:replication:replica:e3980c76

Dockerfile
COPY .pgpass /root/
RUN chown postgres:postgres /root \
 && chown postgres:postgres /root/.pgpass \
 && chmod 0600 /root/.pgpass

docker-entrypoint-initdb.d/init.sh
rm -rf /var/lib/postgresql/data/*
pg_basebackup -h 172.17.0.1 -p 5920 -U replica -D /var/lib/postgresql/data -X stream -P

error
pg_basebackup: could not connect to server: FATAL:  password authentication failed for user "replica"
pg_basebackup: removing contents of data directory "/var/lib/postgresql/data"

**Comment by wglambert** [comment]
>password authentication failed

I don't know what arguments you gave to `docker run` so I can't try to fully reproduce your issue.
Using the environment variables for a postgres user I can connect fine

```console
$ docker run -dit --rm -e POSTGRES_USER=replica -e POSTGRES_PASSWORD=pass --name postgres postgres
2945f2206c6fb0cde32112d574d8c2b2f847629ca932ab0a0766d23080755313

$ docker logs postgres | tail -n 3
2019-02-28 18:05:33.515 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-02-28 18:05:33.542 UTC [59] LOG:  database system was shut down at 2019-02-28 18:05:33 UTC
2019-02-28 18:05:33.550 UTC [1] LOG:  database system is ready to accept connections

$ docker exec -it postgres psql -U replica
psql (11.1 (Debian 11.1-1.pgdg90+1))
Type "help" for help.

replica=#
```

You should try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
