### ISSUE TITLE
Upgrading to jessie?

### ISSUE THREAD

**Issue by louy2** [docker-library/postgres#59]
If I want to use this image with another image which is based on jessie, would it bloat the whole system size? If true, shall I upgrade this image to jessie?

**Comment by tianon** [comment]
It shouldn't bloat your system or cause any kind of incompatibility, but I'm not opposed to updating this image to use `jessie` now that it's officially stable, and since upstream has a `jessie` suite in their repo. :+1:

**Comment by md5** [comment]
:+1: For a `jessie` upgrade.

@tianon It may be good to create a tracking issue in `docker-library/official-images` to track upgrading all `debian`-based images to use `debian:jessie` as a base (where it's possible of course).

**Comment by tianon** [comment]
Since wheezy is still officially supported (and will be for a while yet),
I'm a little hesitant to just say "let's blindly update to jessie
everywhere".  For example, things like MariaDB definitely shouldn't update
yet because upstream doesn't have a jessie repo yet.

So I suppose if someone wanted to go to the work of figuring out a concrete
list of repos that ought to be and can be updated, that'd be :+1:, but then
those bugs might as well be filed on the individual repos, right?

**Comment by md5** [comment]
SGTM
