### ISSUE TITLE
Start and Stop Postgres

### ISSUE THREAD

**Issue by DSSUSER** [docker-library/postgres#609]
Using containers, the container no longer has access to the service, or systemctl commands, because both rely on having access to the underlying kernel.

How do you start and stop the Postgres database / services, inside of the container?

Is there a "Postgres start" and "Postgres stop" command?

**Comment by wglambert** [comment]
You can stop the process using `pg_ctl stop`. When Postgres (PID 1) terminates, the container is terminated as well.
https://www.postgresql.org/docs/devel/app-pg-ctl.html

You can also do a `docker stop` outside the container which will send a `SIGTERM` and if the container hasn't exited in the default 30 seconds a `SIGKILL`
https://docs.docker.com/engine/reference/commandline/stop/

```console
$ docker run -d --rm --name postgres postgres
6a36e2195f9aeef22f6d45a0b10194f06499b008c296e1f1796f98bb15e6ca25

$ docker logs postgres 2>&1 | tail -n 1
2019-09-16 17:16:05.128 UTC [1] LOG:  database system is ready to accept connections

$ docker exec -it postgres bash

root@6a36e2195f9a:/# pg_ctl stop
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.

root@6a36e2195f9a:/# exit
exit

$ docker exec -it --user postgres postgres bash
postgres@6a36e2195f9a:/$ pg_ctl stop
waiting for server to shut down....
```

For questions like this you should try asking/searching the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by wglambert** [comment]
I should also mention that you should mount the database to your local storage, which facilitates restarting the database to the same state it was in when it was shutdown

https://github.com/docker-library/docs/tree/master/postgres#where-to-store-data
