### ISSUE TITLE
[feature request] add less to image

### ISSUE THREAD

**Issue by avkhozov** [docker-library/postgres#613]
Hello,

when using `psql` inside containers, it is very convenient to have a pager with `less` utility. It is possible to a `less` to image?

**Comment by yosifkit** [comment]
While it may be convenient (and small), we try very hard to not add things into the image that are not directly related to running postgres server.

**Comment by programster** [comment]
Apologies for bumping an old issue, but....

I would love to have `less` so that I can disable wrapping of output. E.g. at the moment I am manually installing less into my container, and then I enter the database with:

```
docker exec -e PAGER="/usr/bin/less -S" -it databaseContainerName psql --user myUsername --password -d myDatabaseName
```

Now I can tap my right and left arrow keys to see the output of tables that have a lot of columns, instead of seeing a complete mess. 

**Perhaps there is another solution that doesn't involve installing less?**

**Comment by tianon** [comment]
I would honestly recommend creating a new `psql` image for yourself that has the tools you want (and could then come pre-configured to set `PAGER` appropriately), and connect either via `--network container:xxx`, `--network some-shared-network`, or a shared volume with a unix socket in it.
