### ISSUE TITLE
Configuring Listening Address

### ISSUE THREAD

**Issue by chaddotson** [docker-library/postgres#619]
I've got a general question about how the scripts for version 11 configure the listen address of 0.0.0.0, it doesn't look like it relies directly on a postgresql.conf file but the Dockerfile does take steps to modify the postgresql.conf.sample file.  How are the listening addresses of ipv4 0.0.0.0 and ipv6 :: configured?

**Comment by yosifkit** [comment]
We edit `postgresql.conf.sample` since it is the source of `/var/lib/postgresql/data/postgresql.conf` when [`initdb` runs](https://github.com/docker-library/postgres/blob/a8613f4cda3e932245f09c4d0f6733462b14b582/docker-entrypoint.sh#L75).

See also: https://github.com/docker-library/postgres/issues/105#issuecomment-174083901 and #127.

**Comment by yosifkit** [comment]
See also the "Database Configuration" on the Docker Hub docs (https://hub.docker.com/_/postgres/ and [official-images/docs](https://github.com/docker-library/docs/tree/2720bb8156db16747fb45dce2124fba8ef1fc51a/postgres#database-configuration))

If you are seeing the empty `listen_address` in the entrypoint, that is just for the temporary server that is started for initial setup and `/docker-entrypoint-initdb.d/` scripts

https://github.com/docker-library/postgres/blob/a8613f4cda3e932245f09c4d0f6733462b14b582/docker-entrypoint.sh#L127-L129

**Comment by chaddotson** [comment]
Thanks that was a big help!
