### ISSUE TITLE
Data replication Postgresql 12

### ISSUE THREAD

**Issue by 226284** [docker-library/postgres#629]
I am trying to make the data replication work beetwen two postgres servers on the different addresses.  The thing is, when pg_basebackup command is used, standby can't download data from master. I tried to delete data directory but this stopped the container.

```
$ pg_basebackup -h <master_ip_address> -U replicator -p 5432 -D $PGDATA -Fp -Xs -P -R

Result:

Password:
pg_basebackup: error: directory "/var/lib/postgresql/data" exists but is not empty
```

**Comment by yosifkit** [comment]
Are you running this through a `docker exec` on a second container already running `postgres` server? You'll need to instead have the `pg_basebackup` happen before that server starts (otherwise`$PGDATA` is being actively used by that server instance).

An entrypoint that runs `pg_basebackup` first and then `exec`s to `postgres` should work (taking care to run as the correct user and that `PGDATA` has the proper permissions and ownership). Or you should be able to just `exec docker-entrypoint.sh postgres` at the end to have it ensure proper directory ownership and permissions before starting the database. (based on a quick skim of https://wiki.postgresql.org/wiki/Streaming_Replication#How_to_Use)

Since this isn't a bug with the image, I'll close. Github issues aren't meant to be a support forum, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
