### ISSUE TITLE
Dockerfile for postres11  are failed

### ISSUE THREAD

**Issue by lunyi** [docker-library/postgres#631]
Hi 
It occurs errors when I run
docker build  -f "C:\XXXXX\DockerFile-POSTGRES" -t postgres-db-image "\folder\" 

position here: https://github.com/docker-library/postgres/blob/master/11/Dockerfile#L171

message as the below
COPY failed: stat /var/lib/docker/tmp/docker-builder255843450/docker-entrypoint.sh: no such file or directory

Lunyi

**Comment by wglambert** [comment]
`.../docker-entrypoint.sh: no such file or directory`

You'll want this file https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh in your [build context](https://docs.docker.com/engine/reference/builder/) 

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
