### ISSUE TITLE
persistent storage?

### ISSUE THREAD

**Issue by cdekok** [docker-library/postgres#67]
How to make sure it runs with persistent storage it would help if there would be something about this in the readme.

**Comment by adambair** [comment]
:+1:

**Comment by tianon** [comment]
+1!  This would need to be a PR to
https://github.com/docker-library/docs/blob/9a3c64afc13ef2949b626dc7750b98158b14eef0/postgres/content.md,
probably adding content very similar to what's in mysql:
https://github.com/docker-library/docs/blob/9a3c64afc13ef2949b626dc7750b98158b14eef0/mysql/content.md#where-to-store-data

**Comment by DanielCaldwell** [comment]
+1

I added an example on how I did this here: 

https://github.com/DanielCaldwell/postgres-docker-persistant-data

Maybe it can help someone else.

**Comment by akbargumbira** [comment]
Using docker compose, I can't get the volume working properly. Mounting ```/var/lib/postgresql``` from the container to the host only exposes ```data``` dir without the contain in that dir. If I exec the container, the contain is fine. Anyone has the same problem?

**Comment by yosifkit** [comment]
@akbargumbira, it needs to be mounted to `/var/lib/postgresql/data`, otherwise the docker volume defined there will be mounted on that directory and thus not show up in your bind mount.

**Comment by akbargumbira** [comment]
@yosifkit thanks!

**Comment by akbargumbira** [comment]
@yosifkit btw, I thought it would be recursively mounted? https://github.com/docker/docker/issues/3782

**Comment by iMerica** [comment]
On other official db containers like `redis`, nothing needs to be done to make data persistence work by default. Ideally I can start and stop containers based on this image and have data persists without me having to add `-v` in `docker run` or a custom `VOLUMES` entry in a Dockerfile.

**Comment by md5** [comment]
@iMerica Have you found otherwise with this image? It already has `VOLUME /var/lib/postgresql/data`. I've started and stopped containers based on this image many times and they always come back up with the same data.

This issue seems to be talking about persistence that survives destroying the container. The situation here is the same as every other container with a `VOLUME` statement for its data directory, including `redis`.

**Comment by iMerica** [comment]
Hmm. Yes, data is lost on restarts–and it's happening for everyone in my office. Thanks for your reply, it could be due to the initialization script. I'll open a bug if the issue persists.

**Comment by samueleaton** [comment]
Thanks @yosifkit! I just needed to add `-v /var/lib/postgresql/data:/var/lib/postgresql/data`

**Comment by vytautasgimbutas** [comment]
shouldn't `-v /var/lib/postgresql:/var/lib/postgresql`work as well?

**Comment by yosifkit** [comment]
@vytautasgimbutas, nope :cry:, there is a `VOLUME` declared on [`/var/lib/postgresql/data`](https://github.com/docker-library/postgres/blob/b1831ce069d10b14be05b9ddf6823e3d18c62cee/9.6/Dockerfile#L52), so docker will create that as a separate mount within your bind-mounted directory and you would end up with just an empty `data` folder.

**Comment by wglambert** [comment]
Since this issue seems unrelated to any errors in the image itself, and being two years without further comment, I'm going to prune the issue.
If you believe this to be in error then let me know and I'll re-open it

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
