### ISSUE TITLE
psql login issues in docker-compose

### ISSUE THREAD

**Issue by sajusat** [docker-library/postgres#670]
```
#!/bin/sh

until nc -vz postgresql 5432 &>/dev/null; do
    sleep 1
done

if [ "$( psql -h postgresql -U postgres -w -tAc "SELECT 1 FROM pg_database WHERE datname='devdb'" )" = '1' ]
then
    echo "Database already exists"
else
     echo "Running db creation & init routines"
fi

exec "$@"
```
I have two containers 1. postgresql 2. graphql service (both are alpine based)
I have the above script in my entrypoint.sh which is called as part of the graphql service dockerfile. When I run the container in docker-compose, I get the error as 

```
dss-graphql                 | psql: fe_sendauth: no password supplied
```

I have set the `PGPASSWORD` in the `postgresql` container as well. (also set the `POSTGRES_PASSWORD` just and added measure). 

I can run the command psql command insider container and get the result as `1' as the result. when the same is run from entry point it says `psql: fe_sendauth: no password supplied` 
Any ideas about this behavior ?

**Comment by wglambert** [comment]
>script in my entrypoint.sh

Does your entrypoint.sh include the database initialization from https://github.com/docker-library/postgres/blob/master/12/docker-entrypoint.sh which is how the `POSTGRES_PASSWORD` would be implemented

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by sajusat** [comment]
@wglambert No my entrypoint.sh does not include that one from the link. How do I include that ?

**Comment by wglambert** [comment]
Well to include our entrypoint you would essentially need to use it, then append your script in some way

If your script just wants to create the `devdb` database then there's simple ways of doing that with the image's entrypoint
One is the `postgres_db` env var https://github.com/docker-library/docs/tree/master/postgres#postgres_db
The other is with an [initialization script](https://github.com/docker-library/docs/tree/master/postgres#initialization-scripts)

And for further help you should ask one of the resources I linked above. I'm going to close since this isn't an issue with the image but a usability question and this isn't the appropriate place for it
