### ISSUE TITLE
Main + PG_MAJOR not working in sources.list.d

### ISSUE THREAD

**Issue by hyperknot** [docker-library/postgres#677]
I'm puzzled by this line. 

https://github.com/docker-library/postgres/blob/d21499fa3f55639c6751423e55ff630516bf34e3/11/Dockerfile#L85

According to postgresql IRC channel, 11 **instead** of Main has the purpose of installing client libraries for a specific version, for example libpq5.

However the way it is here, it'll add Main **and** 11, resulting in:

```
 apt-cache policy libpq5
libpq5:
  Installed: 12.2-1.pgdg16.04+1
  Candidate: 12.2-1.pgdg16.04+1
  Version table:
 *** 12.2-1.pgdg16.04+1 500
        500 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main amd64 Packages
        100 /var/lib/dpkg/status
     11.7-1.pgdg16.04+1 500
        500 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/11 amd64 Packages
```

It of course means that the latest version from Main gets installed. Pretty much that makes the whole 11 part useless.

Not a big problem, as the Main version is supposed to be stable, but still, interesting regarding this line was changed from the Main only version some time ago.

**Comment by tianon** [comment]
> Not a big problem, as the Main version is supposed to be stable, but still, interesting regarding this line was changed from the Main only version some time ago.

I dug into the commit history, and found we've had both since https://github.com/docker-library/postgres/commit/2bfa44dab27b6be46333ac7bf86f2517c1479090 (back in 2014).

For anything we install, we're explicit about the version, but this could pull in for dependencies.  I suppose it's worth some testing to see what we'd lose by dropping `main` and going with the version-only APT repository instead.

**Comment by hyperknot** [comment]
The Postgres devs on IRC said that it's only affecting the client libraries, and those can be newer than server versions and are considered pretty stable. In that case maybe it should actually be the opposite, as in leaving only Main?

**Comment by yosifkit** [comment]
Found a reason for keeping both (and needing a pin priority): https://github.com/docker-library/postgres/issues/678#issuecomment-586531632

**Comment by hyperknot** [comment]
Do you mean that in that issue the libpq version has to be exactly the same as the server version?

**Comment by yosifkit** [comment]
Oh, that is not the problem. their Dockerfile builds fine when `FROM postgres 10.12` (current release), but not `10.11` or `10.10`.

It seems that `/usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk` is now part of `postgresql-client-10` (`10.12-1.pgdg90+1`), but is not part of it in `10.11`. I am not sure what older package provided it, but it doesn't matter since older packages are not available through the PostgreSQL apt repo. The solution is to use the newer image.
