### ISSUE TITLE
How to add additional users and databases?

### ISSUE THREAD

**Issue by phlegx** [docker-library/postgres#68]
I can add additionally users and database with `psql` as soon as the postgres server is started.  With this docker image the binary is started via `docker-entrypoint.sh` How can I automate this within my own Dockerfile?

I assume I would need to write a script that I call within my Dockerfile as an entrypoint. This script would need to start the database server, then execute the commands with `psql`and afterwards stop the db server again and let the original `docker-entrypoint.sh`  entrypoint taken place. However I'm not sure: how can I start and stop a postgres server manually within my custom script with this postgres docker image?

thanks
m

**Comment by phlegx** [comment]
Ok I think I simply need to hack into the ```docker-entrypoint.sh``` and replace the original!

**Comment by tianon** [comment]
See https://github.com/docker-library/postgres/blob/bfca9b8a92a99ccfc8f04933b7ecc29a108c7f49/docker-entrypoint.sh#L63-L67 for an easy way to accomplish this without replacing the _entire_ entrypoint script. :+1:

**Comment by uksus70** [comment]
Is it possible to do it using SQL script inside /docker-entrypoint-initdb.d ?

**Comment by xtimon** [comment]
https://github.com/docker-library/postgres/pull/239

**Comment by xtimon** [comment]
https://github.com/docker-library/postgres/pull/240

**Comment by gmile** [comment]
@uksus70 per comment https://github.com/docker-library/postgres/pull/240#issuecomment-314228559 it is possible, yes (I didn't test though)

**Comment by wglambert** [comment]
Since this issue seems unrelated to any errors in the image itself, and being a year without further comment, I'm going to prune the issue.
If you believe this to be in error then let me know and I'll re-open it

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
