### ISSUE TITLE
Not able to apply scripts through installer

### ISSUE THREAD

**Issue by Bibhu14** [docker-library/postgres#695]
DB, username and password created successfully in postgres container.
I am able to connect the DB also through PGAdmin
But while applying the db scripts through installer,database connection error is coming. But can't see any error in log.

PLEASE HELP !!

**Comment by wglambert** [comment]
Can you give all the commands you ran and any logs or files for reproducing the issue

**Comment by Bibhu14** [comment]
docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -e POSTGRES_DB=dockerpg library/
docker exec -it b2512f0621de bash
su postgres
psql
Then i've created tablespaces
after that i'm applying

**Comment by wglambert** [comment]
Up to the step where you create tablespaces works fine as shown here https://github.com/docker-library/postgres/issues/691
I don't know what `after that i'm applying` means, you're running scripts there? But no errors/logs or proper reproducible steps have been shown so I'm closing as a user-issue at this point.

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
