### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by vladyslavstartsev** [docker-library/postgres#708]
I use `FROM postgres:alpine`
I've build my `postgres` service, but when I try to build other service (something like `docker-compose build otherService`)
I get an error
```
PermissionError: [Errno 13] Permission denied: '/home/user/myproject/.data/postgres'
[3923] Failed to execute script docker-compose
```

I think it's due to `700` rights on `/home/user/myproject/.data/postgres` what should I do then? So my user (who executes `docker-compose`) will get rights it.
Currently it has user `70` and group `root` (I don't want to add current user to `root` group due to security).

**Comment by wglambert** [comment]
You'll have to grant it appropriate permissions so that either the `postgres` user can execute the files properly or that all other users can.

I think the easiest solution is have it owned by user `postgres` and granted 770 permissions, but it's ultimately up to what you deem acceptable for your environment

Going to close since this question should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker), as these repos aren't a substitute for a user-help forum

**Comment by vladyslavstartsev** [comment]
@wglambert no it's not a question.
I think it's a bug, because if you run `mysql` or `redis` for example, you will get containers up and running without any problems.

As I said it looks like this 
```bash
drwx------ 19      70 root 4.0K Apr  5 23:44 postgres
```

so there is no `postgres` user in my system (I can't make it own by user, who doesn't exists).
For the 770 permissions, I've found that https://github.com/docker-library/postgres/blob/6d1f671dcd2c8d51484d19767a33c37110dd650f/12/alpine/Dockerfile#L143
I can't set `postgres` container for other dev, because he will get an error. And every new dev on the project will have an error. 
This should be fixed in the image. I can contribute if you want.

**Comment by yosifkit** [comment]
As far as I remember, postgres will not run with a data directory with too wide of permissions.

To run postgres as the user running docker-compose, you would need pre-create the directory as that user and then inject the user id into the [`user:`](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir) field of the yaml. See also the ["Arbitrary --user Notes"](https://github.com/docker-library/docs/blob/32eea2c3abee5c12aa701af411c25cad5fd3b44c/postgres/README.md#arbitrary---user-notes) section of the Docker Hub docs.
