### ISSUE TITLE
Does postgres support two phase commit transaction

### ISSUE THREAD

**Issue by ShubhamKale** [docker-library/postgres#710]
Tried using EJB timer along with postgres, After using XA data source getting exception 

[ERROR   ] WTRN0062E: An illegal attempt to use multiple resources that have onl
y one-phase capability has occurred within a global transaction.
[ERROR   ] J2CA0030E: Method enlist caught java.lang.IllegalStateException: Ille
gal attempt to enlist multiple 1PC XAResources

i tried enabling max_prepared_transaction=100 not worked

**Comment by wglambert** [comment]
It has since 2006 https://www.endpoint.com/blog/2006/05/08/postgresql-supports-two-phase-commit


For help with it you'd want to ask a Postgres resource or some other help forum, this stackoverflow question seems fairly helpful
https://stackoverflow.com/questions/59057621/using-two-phase-commits-on-postgres

**Comment by ShubhamKale** [comment]
Thanks
Found that it is related to some libraries
