### ISSUE TITLE
VERSION=12 FORCE_DEB_BUILD=1 build fails

### ISSUE THREAD

**Issue by birkb** [docker-library/postgres#715]
because of missing packages in the apt repository Packages file. 

- The [VERSION=12 FORCE_DEB_BUILD=1](https://travis-ci.org/github/docker-library/postgres/jobs/675755095#L1047) build fails, but version [12.2-2.pgdg100+1](https://github.com/docker-library/postgres/blob/master/12/Dockerfile#L86) is available in the [repo](http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-12/). 
- http://apt.postgresql.org/pub/repos/apt/dists/buster-pgdg/12/binary-amd64/Packages does not contain the 12.2-2.pgdg100+1 package. 
- `apt-cache search postgresql-12` inside the build container shows no packages. `apt-cache search postgresql-11` lists 64 packages.

**Comment by birkb** [comment]
[PR713](https://github.com/docker-library/postgres/pull/713) is affected by the problem. The related Travis job has been failed.

**Comment by tianon** [comment]
I was looking into this earlier this morning -- this is to make sure that architectures that repository doesn't have binary packages get built for instead, but the problem is that `12.2-2.pgdg100+1` is the latest available version for most architectures *except* `arm64`, which has `12.2-3.pgdg100+1`.  Due to a quirk in how that repository is maintained, only the latter gets listed in the `Sources` manifest file (so even though http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-12/postgresql-12_12.2-2.pgdg100%2B1.dsc exists, our build doesn't find it because `Sources` points us at http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-12/postgresql-12_12.2-3.pgdg100%2B1.dsc :disappointed:).

**Comment by birkb** [comment]
What does it mean for my PR? Is it good enough even if one target fails (for 3rd party reasons)?
