### ISSUE TITLE
log connections show IP from docker-bridge router instead of remote client IP

### ISSUE THREAD

**Issue by ffabreti** [docker-library/postgres#716]
running like
```bash
docker run -d \
--name postgres-jeron1 \
-e POSTGRES_PASSWORD=my-great-pass \
-v /some/point:/var/lib/postgresql/data \
-p 5429:5432  \
 postgres:10.3
 ```
And edited postgresql.conf like
```vim
log_connections = on
```
I receive this on docker logs
```
2020-04-17 19:01:49.505 UTC [29] LOG:  connection received: host=172.17.0.1 port=64676
```
Container is running in bridge mode

Is this intended behaviour ?  Because it makes impossible to trace or filter any connection origin.

```

**Comment by wglambert** [comment]
By default Docker uses a bridge network, you can specify `--network host` however
https://docs.docker.com/network/host/

In the future questions like this should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
