### ISSUE TITLE
Sending RUN ["docker-entrypoint.sh", "postgres", "--version"] output to the console during the build

### ISSUE THREAD

**Issue by doraemoncito** [docker-library/postgres#718]
Apologies if this question has been asked before.  Up until version `10.10` you could see the output of the command in a Docker file that inherited from the `postgres:10.10-alpine` image. E.g. this Dockerfile (cut for brevity):

```Dockerfile
FROM postgres:10.10-alpine
RUN ["docker-entrypoint.sh", "postgres", "--version"]
```

would output  something like this:

```Console
[INFO]  ---> fd92132d5c20
[INFO] Step 10/10 : RUN ["docker-entrypoint.sh", "postgres", "--version"]
[INFO] 
[INFO]  ---> Running in 2a64e24f8df8
[INFO] The files belonging to this database system will be owned by user "postgres".
[INFO] This user must also own the server process.
[INFO] 
[INFO] The database cluster will be initialized with locale "en_US.utf8".
[INFO] The default database encoding has accordingly been set to "UTF8".
[INFO] The default text search configuration will be set to "english".
...
```

Starting at `10.11` the output no longer appears in the console during the build. . E.g. this Dockerfile (again cut for brevity):

```Dockerfile
FROM postgres:12-alpine
RUN ["docker-entrypoint.sh", "postgres", "--version"]
```
Generates this output instead:

```Console
[INFO]  ---> 9e1c212f6bcc
[INFO] Step 10/10 : RUN ["docker-entrypoint.sh", "postgres", "--version"]
[INFO] 
[INFO]  ---> Running in aa64abc39508
[INFO] postgres (PostgreSQL) 12.2
[INFO] Removing intermediate container aa64abc39508
[INFO]  ---> e7eeb9d68edc
[INFO] Successfully built e7eeb9d68edc
```

**Is there any way of getting the earlier `10.10` entry point output behaviour in later versions of the Docker image?**

**Comment by tianon** [comment]
The output no longer appears because `postgres --version` no longer has the side effect of initializing a database (since the arguments passed to `postgres` are now passed to the temporary daemon as well, so it would've completely broken instead of doing what an interactive user would expect, so we changed it to explicitly detect several flags):

https://github.com/docker-library/postgres/blob/a6d35fbd1da31a6a20cbfa6ca7f625a52deef206/docker-entrypoint.sh#L252-L267

See #496 -- this is now possible to accomplish directly without hacks/workarounds like `sed` or `--version`. :+1:

**Comment by doraemoncito** [comment]
> https://github.com/docker-> See #496 -- this is now possible to accomplish directly without hacks/workarounds like `sed` or `--version`. 👍

Brilliant, that's exactly what I was looking for. Thank you.
