### ISSUE TITLE
Postgres to run with logs on stdout

### ISSUE THREAD

**Issue by anuragnc** [docker-library/postgres#765]
I am trying to pick the image from alpine 12.3 but am not being able to control the logs. I would like pg_ctl with no "-l" option.
My Dockerfile looks like this. Is there way I can control it? What is the best way? Any pointer is appreciated. THx

FROM postgres:12.3-alpine
  
COPY initdb.sh /docker-entrypoint-initdb.d/

**Comment by wglambert** [comment]
By default, this image logs to stdout/stderr, which is standard behavior for Docker in order to allow Docker to manage container logging.

You can edit the `/var/lib/postgresql/data/postgresql.conf` 
https://www.postgresql.org/docs/current/runtime-config-logging.html

https://github.com/docker-library/postgres/issues/620#issuecomment-543249358

**Comment by anuragnc** [comment]
Thx wglambert. I am very new to Docker. As I am am using the above Dockerfile, how can I update the conf file as you suggested to turn the logging off and then be used in my container when pg_ctl server is started.

**Comment by wglambert** [comment]
Either by mounting a new .conf over the existing one in the container or set options directly on the run line. Examples in the docs
https://github.com/docker-library/docs/tree/master/postgres#database-configuration

Questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by verydemo** [comment]
postgresql.conf ; The configuration file can only be set to stderr. Is stdout ok? stderr is red log in journald.
