### ISSUE TITLE
database files are incompatible with server

### ISSUE THREAD

**Issue by bartounet16** [docker-library/postgres#766]
Hello.
I use postgres whith guacd docker container
After upgrade all container and debian i have this error in docker postgres container

2020-09-27 19:46:09.877 UTC [1] FATAL:  database files are incompatible with server
2020-09-27 19:46:09.877 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.0 (Debian 13.0-1.pgdg100+1).

**Comment by wglambert** [comment]
For upgrading to newer versions of Postgres Tianon has a repo with upgrade-containers to invoke [pg_upgrade](https://www.postgresql.org/docs/11/upgrading.html#UPGRADING-VIA-PG-UPGRADE) 
https://github.com/tianon/docker-postgres-upgrade
Postgres [documentation](https://www.postgresql.org/docs/11/upgrading.html#UPGRADING-VIA-PG-UPGRADE) on `pg_upgrade`

https://github.com/docker-library/postgres/issues/37#issuecomment-404598989
>There actually is support for migrating data files in PostgreSQL, it's called [pg_upgrade](https://www.postgresql.org/docs/current/static/pgupgrade.html). The Docker container is special in that it's difficult to use this support because it needs both the older and the newer versions installed on the same system. The Docker container isn't set up to work this way. Alternately, you can also look into replication if you have large data sets or absolutely can't have any downtime. Options are actually discussed on this [official documentation page](https://www.postgresql.org/docs/current/static/upgrading.html).

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by bartounet16** [comment]
Thanks for answer
Excuse me for my english.
I don't understand why it was work like a charm and suddently not...

Because Upgrade my Debian Host ?
Because upgrade Docker container postgres ?
Because upgrade Docker container Guacd ?

I don't understand what i will to do ...

**Comment by wglambert** [comment]
>The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.0

Use `postgres:12` as that's the version that initialized your database

Questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by Vasiliy566** [comment]
thx @wglambert , work for me
