### ISSUE TITLE
pgpool integration : passwordless SSH

### ISSUE THREAD

**Issue by mgonzaga1990** [docker-library/postgres#771]
Hi,

Would like to check if this part below is doable.

```
[all servers]# cd ~/.ssh
[all servers]# ssh-keygen -t rsa -f id_rsa_pgpool
[all servers]# ssh-copy-id -i id_rsa_pgpool.pub postgres@server1
[all servers]# ssh-copy-id -i id_rsa_pgpool.pub postgres@server2
[all servers]# ssh-copy-id -i id_rsa_pgpool.pub postgres@server3

[all servers]# su - postgres
[all servers]$ cd ~/.ssh
[all servers]$ ssh-keygen -t rsa -f id_rsa_pgpool
[all servers]$ ssh-copy-id -i id_rsa_pgpool.pub postgres@server1
[all servers]$ ssh-copy-id -i id_rsa_pgpool.pub postgres@server2
[all servers]$ ssh-copy-id -i id_rsa_pgpool.pub postgres@server3
```

I tried that and got the permission error.
![image](https://user-images.githubusercontent.com/21145779/95385304-5be0e180-0920-11eb-8f2b-08d20b9dfae6.png)

So I'm wondering if this is possible or is there any other way of doing this inside the container?

**Comment by mgonzaga1990** [comment]
Updated 

from my pgpool server I'm trying to run a `ssh-copy` but got this error

![image](https://user-images.githubusercontent.com/21145779/95389412-5d150d00-0926-11eb-974c-f48ea4e10518.png)

pg-10 is where i'm running my container for postgres-12

**Comment by yosifkit** [comment]
The postgres images do not have an ssh server installed, nor would it run since there is no `init` in the container. Only the postgres server is running (after the entrypoint shell script finishes initial setup).

**Comment by mgonzaga1990** [comment]
Thanks @yosifkit , but how about putting a script under `docker-entrypoint-initdb.d` ? after i install ssh server? like i extend the image itself? would that be a possible workaround?

**Comment by yosifkit** [comment]
Certainly you *could* start an ssh server in the background but it is definitely not a supported use of the `initdb.d` scripts. One large reason being that if you want to run multiple processes in a container, then you need to use something designed to be a supervisor in order to monitor/maintain those processes (`supervisord`, `s6`, etc).

Since there isn't a problem within the postgres image, I will close the issue. For further help, try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
