### ISSUE TITLE
Running .sql files on docker-entrypoint dir

### ISSUE THREAD

**Issue by chbrandt** [docker-library/postgres#81]
At [docker-entrypoint:sh:88](https://github.com/docker-library/postgres/blob/master/9.4/docker-entrypoint.sh#L88), shouldn't the username (for running the '.sql' scripts) be `$POSTGRES_USER`?

**Comment by md5** [comment]
@chbrandt Why did you close this? It seems like a valid question.

**Comment by chbrandt** [comment]
@md5 because `POSTGRES_USER` has the properties `NOCREATEDB`, `NOCREATEROLE` and `NOREPLICATION`, and for some reason I thought that would be necessary. But, in fact, it isn't since `POSTGRES_USER` is playing in its [own db](https://github.com/docker-library/postgres/blob/master/9.4/docker-entrypoint.sh#L64), `POSTGRES_DB`.
Since I'm newbie, at some point I thought I was wrong. Anyway, if I asked, I should wait some one to answer it...
[]

**Comment by md5** [comment]
@chbrandt Good point. Since the user is given `SUPERUSER`, I suppose it would be possible to use that permission to give the user `CREATEDB` or any of the other permissions as needed in a `*.sql` file. Since the globbing in bash guarantees an order, it would be a simple matter to ensure that the script that grants those permissions would be run first based on a naming convention.
