### ISSUE TITLE
Require steps to configure Kerberos on Postgres deployed on Redhat openshift platform

### ISSUE THREAD

**Issue by BANSAL-PALLAVI** [docker-library/postgres#823]

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by wglambert** [comment]
Closing since there's nothing actionable for us to do here. If you're suggesting that documentation be added for configuring Kerberos on Postgres deployed on Redhat's openshift then it's outside the scope of this repository.

If you were looking for help with a question related to this then you could try asking an OpenShift-specific resource or possibly the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
