### ISSUE TITLE
connect to postgresql from Ubuntu on WSL2

### ISSUE THREAD

**Issue by VikingExplorer** [docker-library/postgres#829]
Through Docker Desktop, I created 3 docker images.  I'm able to connect to each of these database from Windows 10.

Now, I want to connect to them from an application running on Ubuntu/WSL2.   When I try, the software malfunctions at that point.  How can I connect to postgresql from Ubuntu on WSL2?

Aspen:/mnt/c/Users/gunna$ docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED       STATUS          PORTS                                NAMES
cd3dc74b8aa6   mysql:8.0.23                                 "docker-entrypoint.s…"   7 weeks ago   Up 6 seconds    33060/tcp, 0.0.0.0:33060->3306/tcp   DockerMySql
9247adb073ea   postgres                                     "docker-entrypoint.s…"   7 weeks ago   Up 9 seconds    0.0.0.0:54320->5432/tcp              DockerPostgreSQL
c9b21301a315   mcr.microsoft.com/mssql/server:2019-latest   "/opt/mssql/bin/perm…"   7 weeks ago   Up 12 seconds   0.0.0.0:14330->1433/tcp              DockerSQL_SRVR
g

**Comment by wglambert** [comment]
Any specific errors that you're getting? You should be able to connect to the IP of the Win10 host at Postgres' published port `54320`

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by VikingExplorer** [comment]
I think you gave me the answer.  I was trying to connect at localhost.  It seemed counter-intuitive to connect from ubuntu using the IP address of the Win10 host.  However, it seems to be working now.  Thank you so much!
