### ISSUE TITLE
 init-user-db.sh:/bin/bash: bad interpreter: Permission denied

### ISSUE THREAD

**Issue by NaUyLL** [docker-library/postgres#850]
When I use '.yml' to docker compose my app, there was an error.
`/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-user-db.sh
/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/init-user-db.sh: /bin/bash: bad interpreter: Permission denied`

The volume setting is `./pg-init-scripts:/docker-entrypoint-initdb.d`. And the init-user-db.sh is in folder pg-init-scripts.
 Version 6.9.0 works normally, but errors will be reported in versions 6.9 or 6.9.22. 

What is probably the cause of this problem?
In addition, all of these are running on the MacOS system.

**Comment by wglambert** [comment]
The `Permission denied` is the main thing, you'd want to make sure whatever is being mounted has appropriate permissions for the user running in the container

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by whizyrel** [comment]
I suggest you change ownership of the files or directories and maybe make it executable (if you eventually have correlating error).
```
# directory with files in it, recursively
$ sudo chown -R 999:999 ./pg-init-scripts
# file
$ sudo chown 999:999 ./init-user-db.sh

# executable, grants execution for all
$ sudo chmod +x ./pg-init-scripts/init-user-db.sh
```
