### ISSUE TITLE
Cannot unset/delete ENV vars in Postgres container via script

### ISSUE THREAD

**Issue by petef19** [docker-library/postgres#869]
In order to leave as little as possible of sensitive data inside the container, I tried to unset/remove ENV vars (set via Docker) in the container running a shell script - can NOT get this to work. Tried on Alpine release as well as full release image.

this is the shell init script that is copied by the Dockerfile into the entrypoint - it does get auto executed but it does not delete the ENV var:
```
unset POSTGRES_PASSWORD
```

other things I've tried:
(1) copy script to a  different location in container and then manually trigger this script via `ENTRYPOINT` cmd from Dockerfile
(2) copy script to a  different location in container and then manually trigger this script `CMD` cmd from Dockerfile

None work.

When I manually jump into the container and run `printenv` I see the env var. When I then run `unset POSTGRES_PASSWORD` the env var is deleted.

So why can't the shell script not achieve this ?

stack:
Docker Desktop for Windows 3.5.2 (66501)
Win 10 x64
Postgres 13.3

**Comment by wglambert** [comment]
Scripts run as a subshell https://tldp.org/LDP/abs/html/subshells.html to have it affect environment variables of the parent shell you'll want to `source` the script.

```console
$ docker run -e test_env=1 -it --rm bash

bash-5.1# echo "unset test_env" > script.sh && chmod +x script.sh

bash-5.1# ./script.sh 

bash-5.1# env | grep test_env
test_env=1
```
Variable is still there, but sourcing the file will run it in the parent shell
```console
bash-5.1# source script.sh 

bash-5.1# env | grep test_env
```

Since this isn't an issue with the image I'm going to close, in the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by petef19** [comment]
>  in the future questions like these should be asked over at the...

apologies, but I encountered this with the Docker Postgres image hence not sure where the exact problem lies

re your code example:
this does work in your isolated test running a docker container directly, but consider this test set up via `docker-compose`:

docker-compose.yml
```
version: '3.6'

services:
  postgres_test:
    container_name: postgres_13_3
    image: postgres_13_3
    restart: unless-stopped
    build:
      context: ./postgres
      dockerfile: postgres_13_test.dk
    environment:
        POSTGRES_PASSWORD: 'test'
```

postgres_13_test.dk - trying to unset the env var via a script
```
FROM postgres:13.3-alpine3.14

COPY ./unset.sh /unset.sh
RUN chmod +x /unset.sh
RUN source /unset.sh
```

unset.sh
```
unset POSTGRES_PASSWORD
```

when you run `docker-compose-up --build` and wait for the container to be up and running, and you then jump into the container via `docker exec -it postgres_13_3 /bin/sh`, and then run `env | grep POSTGRES_PASSWORD`, you will get:
`POSTGRES_PASSWORD=test`

the env var still exists...

**Comment by yosifkit** [comment]
`RUN source /unset.sh` would only unset the variable for the specific shell process that ran for the `RUN` line.

The process that you want to hide the env from needs to be a child process of the process that removed it.  In docker, this will never happen for an `exec` since it takes the env state from docker's knowledge, not from a process currently running in the container.  Docker will always have a view of environment variables that were set:

```console
$ docker run -it --rm --name pg -e POSTGRES_PASSWORD=12345 postgres
...
$ # another terminal
$ docker container inspect --format '{{json .Config.Env}}' pg | jq '.'
[
  "POSTGRES_PASSWORD=12345",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/13/bin",
  "GOSU_VERSION=1.12",
  "LANG=en_US.utf8",
  "PG_MAJOR=13",
  "PG_VERSION=13.3-1.pgdg100+1",
  "PGDATA=/var/lib/postgresql/data"
]
```

**Comment by petef19** [comment]
@yosifkit  thanks for your explanation
