### ISSUE TITLE
when use dbname has "gis*" string, docker can not restart container

### ISSUE THREAD

**Issue by year112** [docker-library/postgres#873]
user postgresql v9.6
when i create db name "gis-server" and config with docker-compose volumes /data/gisdata:/var/lib/postgressql ,exec docker restart the container, some problems in logs
ERROR: databases "gis" already exists
i can not restart the docker container
when i rename db "gis-server" to "dbserver" ,it's restart fine.

**Comment by wglambert** [comment]
Going to close assuming you fixed the issue. You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
