### ISSUE TITLE
Question: what is the proper way to update postgresql.auto.conf settings?

### ISSUE THREAD

**Issue by oerp-odoo** [docker-library/postgres#903]
When starting postgres container, currently I pass this on my compose:

    volumes:
      - ./config.sql:/docker-entrypoint-initdb.d/config.sql

File consists of `ALTER SYSTEM` instructions, telling to tune postgresql. It works fine, when container is created initially. But what if I want to update those parameters later? `docker-entrypoint-initdb.d` dir is checked only initially.

What would be the proper way to force update parameters?

**Comment by wglambert** [comment]
Yeah the initialization script that executes files in `docker-entrypoint-initdb.d/` only runs when there's no existing database, so if you want to modify any parameters later you'd have to do it manually https://github.com/docker-library/docs/tree/master/postgres#initialization-scripts

**Comment by oerp-odoo** [comment]
So I guess I should something like `$ docker run -d --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword postgres -c shared_buffers=256MB -c max_connections=200
` ?

**Comment by wglambert** [comment]
Sure passing arguments to postgres is another way. But if you wanted to update those parameters later it'd still have to be done manually

[https://www.postgresql.org/docs/current/config-setting.html](https://www.postgresql.org/docs/current/config-setting.html#:~:text=WHERE%20name%20%3D%20'configuration_parameter'%3B-,20.1.4.%20parameter%20interaction%20via%20the%20shell,-In%20addition%20to)

>During server startup, parameter settings can be passed to the postgres command

**Comment by tianon** [comment]
Yeah, I think setting parameters via container command at runtime is the easiest way to set additional settings _and_ be able to easily change them later.  Otherwise, you'll want/need to edit the `conf` file directly in the volume.

(For more help, I'd suggest a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).)
