### ISSUE TITLE
Can not drop dac_override capability because of docker-entrypoint.sh

### ISSUE THREAD

**Issue by mwester117** [docker-library/postgres#907]
Currently the container needs the capability dac_override. This is a potential security issue also mentioned in [this Red Hat article.](https://www.redhat.com/en/blog/secure-your-containers-one-weird-trick)
In Issue #208 and pull request #209 this issue was fixed but was reintroduced later.

If I drop the capability dac_override on an already initialized postgres installation serveral "permission denied" errors appear in the logs:
`find: /var/lib/postgresql/data: Permission denied`

You can workaround this error if you change the following line to `chmod 750 "$PGDATA" || :`
https://github.com/docker-library/postgres/blob/a11e908fb50cacb6192d1db93dcf911bc1a724e6/docker-entrypoint.sh#L41
The group of the files is "root" in this case. This is the reason why dac_override is not needed anymore and the find command can operate on the files anyway.

I'm not sure if this is only a fix for already initialized databases. Maybe other fixes are needed to be sure that dac_override can be dropped on non initialized databases.

For security reason it would be really great if we can drop the dac_override capability for this container again.

**Comment by tianon** [comment]
Ah interesting -- if we run the container as non-root, it doesn't run that code at all, and the cap drop works just fine.  I'd honestly suggest doing that for any/all security conscious users rather than relying on our code that does a drop from root after munging permissions.

See https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes for some details about how to do that successfully.

**Comment by mwester117** [comment]
Hello @tianon,
thanks for your advise. With --user the container works perfectly with dropping all capabilities and for me the issue can be closed.
