### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by guai** [docker-library/postgres#933]
I'm running this image (postgres:latest) in openshift

The first line in the logs contains this error:
`changing permissions of '/var/run/postgresql': Operation not permitted`
then:
`2022-02-14 15:54:28.644 UTC [41] FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": Permission denied`

I've already changed `PGDATA` to `/var/lib/postgresql/data/mydata`
And `unix_socket_directories = '/tmp'` in `/var/lib/postgresql/data/mydata/postgresql.conf`
But it didn't help

**Comment by wglambert** [comment]
See running as non-root https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes

Found this blog post that might help you https://suedbroecker.net/2020/06/23/run-a-postgressql-container-as-a-non-root-user-in-openshift/

But otherwise I would try asking an Openshift/Kubernetes specific resource since these repos aren't really a user-help forum
