### ISSUE TITLE
sshfs as postgres volume

### ISSUE THREAD

**Issue by JeremiasIsnardy** [docker-library/postgres#939]
Hello,

I try to use a sshfs volume with postgres.

sshfs: https://github.com/vieux/docker-volume-sshfs
docker version:  Docker version 20.10.11, build dea9396

The sshfs is working, I'm able to read and write data in general, when using it as a volume.
But when I want to use it as a volume for postgres to save the pgdata, I'm facing some issue.

How to reproduce:

`
docker volume create -d vieux/sshfs \
 -o allow_other \
 -o sshcmd=xxx@yyy:/zzz 
 -o password=uuu  testvol
`

I teste the following scenarios:

- withouth chaning folder for pg data
`
docker run --name testdb\
  -e POSTGRES_PASSWORD=test \
  -v testvol:/var/lib/postgresql/data postgres
`

This returns in the issue:
`docker: Error response from daemon: failed to copy file info for /var/lib/docker/plugins/9b724c6a6c0c295e04f9e645ed963fcf37f1aad23c7b1942f36affbab6128e85/propagated-mount/1876ac7c4f4f872f76be571a260b5242: failed to chown /var/lib/docker/plugins/9b724c6a6c0c295e04f9e645ed963fcf37f1aad23c7b1942f36affbab6128e85/propagated-mount/1876ac7c4f4f872f76be571a260b5242: lchown /var/lib/docker/plugins/9b724c6a6c0c295e04f9e645ed963fcf37f1aad23c7b1942f36affbab6128e85/propagated-mount/1876ac7c4f4f872f76be571a260b5242: permission denied.`

-  changing pg data directory
`docker run --name testdb2\
  -e POSTGRES_PASSWORD=test \ 
  -e PGDATA=/pgdata  \
  -v testvol:/pgdata postgres
`

results in

`chown: changing ownership of '/pgdata': Permission denied`

My host system is Windows.
When I use a local volume, all works out.
And as I mentioned, using sshfs is in general also possible (just having issues with postgres in the constellation)

I tried alredy:
- using only root
- creating folders upfront and do a chown for postgres user

Thanks in advance!

**Comment by yosifkit** [comment]
PostgreSQL server is very particular about the ownership of files (and folders). If `initdb` is not running as the owner of the folder it will just fail and exit. So, the entrypoint script will `chown` them all to the `postgres` user (and then drop down to the `postgres` user) if the container is started as root.

But, if you start `postgres` as the owner UID/GID of the data folder then it might work. (I assume there is a way to control the ownership presented by the sshfs volume).

```console
(this is just from a mkdir, not actually using sshfs)
$ docker run -it --rm -v testvol:/pgdata postgres:14 ls -lan /pgdata/
total 8
drwxr-xr-x 2 1000 1000 4096 Feb 28 17:51 .
drwxr-xr-x 1    0    0 4096 Feb 28 17:51 ..
$ docker run --name testdb2 -e POSTGRES_PASSWORD=test -e PGDATA=/pgdata -v testvol:/pgdata --user 1000:1000 postgres:14
```

If the owner is `0`, then it likely won't be possible without changing sshfs to present a different UID since, I think, `initdb` refuses to run in that instance (and our entrypoint script doesn't have a way to not step down from root).

**Comment by wglambert** [comment]
Closing since this seems resolved, if you need further help you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)
