### ISSUE TITLE
Stopping PostgreSQL to restore backup with pgbackrest

### ISSUE THREAD

**Issue by MichaelJendryke** [docker-library/postgres#942]
Dear all, I use the official postgres docker image and I have a pgbackrest backup on an S3 bucket. In order to run the pgbackrest command to restore, the PostgreSQL service needs to be stopped. How can I stop (and later start) postgres inside the docker container without shutting down the entire container. I'd like to maintain my `docker exec` session, turn off postgres, run the pgbackrest command and start the server again. `pg_ctl -D /path stop -w` kills the entire container. What is the correct command? Thanks!

**Comment by tianon** [comment]
See #922 -- by default, PostgreSQL runs as "PID 1" within the container, so when it stops, the entire container is killed (as you've noted).  If you don't want this behavior, you'll need to run something else as PID 1 (such as `bash`) and start the PostgreSQL server separately (or run your "offline" commands in a new separate container while the main one is stopped instead of trying to re-use your PostgreSQL container).

In the future, these sorts of questions/requests would be more appropriately posted to a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
