### ISSUE TITLE
Init database aside the main container

### ISSUE THREAD

**Issue by Bricklou** [docker-library/postgres#971]
I'm currently using postgres inside a K3S cluster and I met a big problem when I wanted to use probes: since the initialization part always take a long time to finish, I need to adjust a big value to `initialDelaySeconds` on my deployment.

Would it be possible to add a way where we can just call the `postgres` image using `initContainers` to set up the database and then boot the database as usual ?

**Comment by wglambert** [comment]
Not sure which probe you're using but a [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes) with a [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) that tries to exec psql in the Postgres container would probably be the easiest way of doing it

Not sure exactly why you'd want to use an initcontainer since Postgres will just initialize and sit there waiting for connections. If you wanted to customize its initialization you can pass it scripts https://github.com/docker-library/docs/tree/master/postgres#initialization-scripts

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by Bricklou** [comment]
i'm using both `readinessProbe` and `livenessProbe` with `pg_isready`. But they kill the pod before it finish to initialize the database folder for the first boot (the entrypoint script).

**Comment by tianon** [comment]
See also https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes which specifically talks about startup probes for "applications that might require an additional startup time on their first initialization" :eyes:
