### ISSUE TITLE
Is there any difference in performance or other aspects between alpine and debian versions of postgres?

### ISSUE THREAD

**Issue by luomengY** [docker-library/postgres#986]
Is there any difference in performance or other aspects between alpine and debian versions of postgres?

**Comment by luomengY** [comment]
I see that alpine is installed by compiling the pg source package in the Docketfile, but debian is installed directly using apt-get in the Dockerfile. What do I need to do if debian is also installed by compiling from source? Because I made my own modifications to the pg source code.

**Comment by wglambert** [comment]
To my knowledge there aren't any performance discrepancies in Postgres between the variants. For what you're wanting I think Alpine's Dockerfile is probably the easiest to derive from

I imagine it's simple as substituting the wget and checksum validation with your own tarball
https://github.com/docker-library/postgres/blob/271cf940d0b8e212d16309271d49a8fdd4f48978/15/alpine/Dockerfile#L29-L32

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by stephane-klein** [comment]
@luomengY 3 years later, have you found a factual answer to your question?
