### ISSUE TITLE
The dokcerfile of the docker build alpine version reports an error: postgres --version' returned a non-zero code: 2.

### ISSUE THREAD

**Issue by luomengY** [docker-library/postgres#987]
The dokcerfile of the docker build alpine version reports an error: postgres --version' returned a non-zero code: 2.

**Comment by wglambert** [comment]
Same as https://github.com/docker-library/postgres/issues/988
I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
