### ISSUE TITLE
What parameters need to be passed in when running the update.sh script, can you write a demo? I am very grateful!

### ISSUE THREAD

**Issue by luomengY** [docker-library/postgres#990]
What parameters need to be passed in when running the update.sh script, can you write a demo? I am very grateful!

**Comment by yosifkit** [comment]
The only arguments it takes are which versions to try to find updates for ( via`versions.sh`) and apply any changes (via `apply-templates.sh`); for examples `./update.sh 14` or `./update.sh 12 10 13`.

https://github.com/docker-library/postgres/blob/271cf940d0b8e212d16309271d49a8fdd4f48978/update.sh#L6-L7

If no arguments are given, then these scripts attempts to do so for all versions in the repo.  The `update.sh` script does not usually need to be run manually, since there is an automated job that runs it and commits the changes.

---

If making a pull request to change the Dockerization, then changing the `Dockerfile-alpine.template` or `Dockerfile-debian.template` files is the correct approach followed by running `apply-templates.sh` and committing the changes. (which also works for changing the `docker-entrypoint.sh` at the root of the repo and applying the change to all the versions; but it does not currently use templating).
