### ISSUE TITLE
 replication slot "stolon_674502be" does not exist

### ISSUE THREAD

**Issue by luomengY** [docker-library/postgres#991]
replication slot "stolon_674502be" does not exist

**Comment by luomengY** [comment]
skipping special file "./postgresql.auto.conf"

**Comment by wglambert** [comment]
I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) and including more information on reproducing the error like any relevant files and `docker logs`. Since these repos aren't really a user-help forum
